(defpackage #:tomoe
  (:use #:cl)
  (:export #:define-extension #:context #:place #:focus #:bind-key
           #:launch #:close-window #:quit #:reload))
(defpackage #:tomoe-user (:use #:cl #:tomoe))
(in-package #:tomoe)

(defconstant +wire-version+ 1)
(defparameter +context-keys+ '(:windows :outputs :layout :focus :bindings :key :button))
(defvar *definitions* :not-loading)
(defvar *source*)

(defun copy-data (value)
  "Copy bounded Lisp data. No closures, host handles, shared strings, or cycles cross dispatch."
  (let ((nodes 0))
    (labels ((walk (item depth)
               (when (or (> (incf nodes) 32768) (> depth 64))
                 (error "Extension data exceeds the node/depth budget."))
               (typecase item
                 (null nil)
                 (cons
                  (let ((items nil) (tail item))
                    (loop while (consp tail) do
                      (when (> (incf nodes) 32768) (error "Extension data exceeds the node budget."))
                      (push (walk (car tail) (1+ depth)) items)
                      (setf tail (cdr tail)))
                    (nreconc items (walk tail (1+ depth)))))
                 (string
                  (when (> (length item) 65536) (error "String exceeds 65536 characters."))
                  (copy-seq item))
                 (integer
                  (unless (<= (- (expt 2 63)) item (1- (expt 2 64)))
                    (error "Integer outside the data range."))
                  item)
                 (symbol
                  (unless (or (eq item t) (keywordp item))
                    (error "Only keywords, T, and NIL are data symbols: ~S" item))
                  item)
                 (t (error "Not extension data: ~S" (type-of item))))))
      (walk value 0))))

(defstruct (snapshot (:constructor make-snapshot (data reads)))
  (data nil :read-only t) (reads nil :read-only t))
(defun context (snapshot key)
  "Read a declared context key. Values belong to this invocation, not the host."
  (unless (member key (snapshot-reads snapshot))
    (error "Undeclared context dependency: ~S" key))
  (getf (snapshot-data snapshot) key))

(defstruct (effect (:constructor %effect (kind arguments)))
  (kind nil :read-only t) (arguments nil :read-only t))
(defstruct (command (:constructor %command (kind arguments)))
  (kind nil :read-only t) (arguments nil :read-only t))

(defun place (id x y width height &optional (visible t))
  (check-type id (integer 1 4294967295))
  (check-type x (integer -1048576 1048576))
  (check-type y (integer -1048576 1048576))
  (check-type width (integer 1 16384))
  (check-type height (integer 1 16384))
  (check-type visible boolean)
  (%effect :place (list id x y width height visible)))
(defun focus (id)
  (check-type id (or null (integer 1 4294967295)))
  (%effect :focus (list id)))
(defun bind-key (modifiers keysym command)
  (check-type keysym string)
  (check-type command keyword)
  (when (or (zerop (length keysym)) (find #\Null keysym)) (error "Invalid keysym name."))
  (let ((mask 0))
    (dolist (modifier modifiers)
      (setf mask (logior mask (ecase modifier (:shift 1) (:control 4) (:alt 8) (:super 64)))))
    (%effect :bind (list mask (copy-seq keysym) (string-downcase command)))))
(defun launch (&rest argv)
  (unless argv (error "LAUNCH requires an executable and optional arguments."))
  (dolist (arg argv)
    (check-type arg string)
    (when (find #\Null arg) (error "NUL in process argument.")))
  (when (zerop (length (first argv))) (error "Empty executable name."))
  (%command :launch (copy-data argv)))
(defun close-window (id)
  (check-type id (integer 1 4294967295))
  (%command :close (list id)))
(defun quit () (%command :quit nil))
(defun reload () (%command :reload nil))

(defstruct spec name reads initial update source)
(defun register-spec (name reads initial update)
  (when (eq *definitions* :not-loading) (error "Load declarations with MOUNT or RELOAD."))
  (check-type name string)
  (unless (and (<= 1 (length name) 80)
               (every (lambda (c) (or (find c "-_./") (alphanumericp c))) name))
    (error "Invalid extension name: ~S" name))
  (dolist (key reads)
    (unless (member key +context-keys+) (error "Unknown dependency: ~S" key)))
  (when (find name *definitions* :key #'spec-name :test #'equal)
    (error "Duplicate extension: ~A" name))
  (push (make-spec :name (copy-seq name) :reads (copy-list reads)
                   :initial (copy-data initial) :update update :source *source*)
        *definitions*))

(defmacro define-extension (name (&key reads state) (snapshot state-name event) &body body)
  "Declare a pure reducer. Return three values: state, owned effects, one-shot commands."
  `(register-spec ,name ',reads ,state
                  (lambda (,snapshot ,state-name ,event) ,@body)))
