#!/usr/bin/env python3
"""Emit Lisp interface tables from a wayland-protocols XML file.

Usage: gen-protocols.py xdg-shell.xml > xdg-shell.lisp

Opcodes and signatures come from the XML, never from transcription.
"""
import sys
import xml.etree.ElementTree as ET

def wanted():
    return sys.argv[2:]

# wayland-scanner derives the wire signature from these argument types.
LETTER = {"int": "i", "uint": "u", "fixed": "f", "string": "s",
          "object": "o", "new_id": "n", "array": "a", "fd": "h"}


def signature_of(args):
    """wayland-scanner's encoding: version prefix, then ? for nullable, then the letter."""
    out = []
    for arg in args:
        since = int(arg.get("since", "1"))
        if since > 1:
            out.append(str(since))
        if arg.get("allow-null") == "true":
            out.append("?")
        out.append(LETTER[arg.get("type")])
    return "".join(out)


def messages(node):
    out = []
    for index, message in enumerate(node):
        args = message.findall("arg")
        signature = signature_of(args)
        types = " ".join('"%s"' % (arg.get("interface") or "") for arg in args)
        out.append((index, message.get("name"), signature, types))
    return out


def emit(interface):
    name = interface.get("name")
    print('   ("%s" %s' % (name, interface.get("version")))
    for group, tag in (("requests", "request"), ("events", "event")):
        print("    (")
        for index, message, signature, types in messages(interface.findall(tag)):
            print('     (%d "%s" "%s" (%s))' % (index, message, signature, types))
        print("    )")
    print("    )")


def main(path):
    WANTED = wanted()
    print(";; Generated by gen-protocols.py from %s. Do not edit by hand." % path.rsplit("/", 1)[-1])
    print("(in-package #:tomoe)")
    print()
    stem = path.rsplit("/", 1)[-1]
    name = "+core-protocol-tables+" if stem == "wayland.xml" else "+%s-protocol-tables+" % stem[:-4]
    print("(defparameter %s" % name)
    print("  '(")
    root = ET.parse(path).getroot()
    seen = set()
    for interface in root.findall("interface"):
        if interface.get("name") in WANTED:
            emit(interface)
            seen.add(interface.get("name"))
    print("    ))")
    missing = [name for name in WANTED if name not in seen]
    if missing:
        print(";; MISSING: %s" % " ".join(missing), file=sys.stderr)
        return 1
    return 0


sys.exit(main(sys.argv[1]))
