(in-package #:tomoe-user)


(define-extension "wm"
    (:reads (:windows :rules :data :outputs :workareas :layout :focus :button :pointer :key :request
             :settings)
     :state nil :admission t)
    (snapshot state event)
  (let* ((windows (context snapshot :windows))
         (ids (mapcar (lambda (window) (getf window :id)) windows))
         (settings (state-value snapshot :wm-settings))
         (gap (getf settings :gaps 8))
         (count (getf settings :workspace-count 9))
         (honor (getf settings :honor-client-fullscreen nil))
         (outputs (context snapshot :outputs))
         (workareas (context snapshot :workareas))
         (output (first outputs))
         (area (or (find (getf output :name) workareas :test #'equal
                                                       :key (lambda (entry) (getf entry :name)))
                   output))
         (layout (context snapshot :layout))
         (input-layout (previous-context snapshot :layout))
         (old-ids (getf state :ids))
         (removed (set-difference old-ids ids))
         (new-ids (set-difference ids old-ids))
         (active (getf state :active 1))
         (workspaces nil)
         (full (remove-if-not (lambda (entry) (member (getf entry :id) ids))
                              (getf state :fullscreen)))
         (maximized (intersection (getf state :maximized) ids))
         (boxes (remove-if-not (lambda (entry) (member (getf entry :id) ids))
                               (getf state :boxes)))
         (stack (remove-if-not (lambda (id) (member id ids)) (getf state :stacking)))
         (visible (remove-if-not (lambda (id) (member id ids)) (getf state :visible)))
         (focused (getf state :focused))
         (type (getf event :type))
         (geometry-key (list outputs workareas gap count))
         (retired-full nil)
         (commands nil))
    (check-type gap (integer 0 16384))
    (check-type count (integer 1 128))
    (check-type honor boolean)
    (setf active (max 1 (min count active))
          workspaces
          (loop for index below count
                collect (remove-if-not (lambda (id) (member id ids))
                                       (nth index (getf state :workspaces)))))
    (labels ((workspace (number) (nth (1- number) workspaces))
             (append-window (number id)
               (setf (nth (1- number) workspaces)
                     (append (workspace number) (list id))))
             (window-box (id) (find id boxes :key (lambda (entry) (getf entry :id))))
             (full-box (id) (find id full :key (lambda (entry) (getf entry :id))))
             (remember-box (id x y width height)
               (let ((box (list :id id :x x :y y :width (max 1 width) :height (max 1 height))))
                 (setf boxes (cons box (remove id boxes :key (lambda (entry) (getf entry :id)))))
                 box))
             (raise-id (id)
               (when (member id visible)
                 (setf stack (append (remove id stack) (list id)))))
             (show-id (id)
               (unless (member id visible)
                 (push id visible)
                 (setf stack (append (remove id stack) (list id)))))
             (hide-id (id)
               (setf visible (remove id visible) stack (remove id stack)))
             (focus-id (id)
               (setf focused id)
               (when id (raise-id id)))
             (current-focus ()
               (let ((previous (previous-context snapshot :focus)))
                 (if (not (eql previous (getf state :focused)))
                     (when (member previous ids) previous)
                     (when (member focused ids) focused))))
             (properties (id) (rules-for snapshot id))
             (property (properties name)
               (let ((entry (or (assoc name properties)
                                (assoc (string-downcase (symbol-name name)) properties :test #'equal))))
                 (values (cdr entry) (not (null entry)))))
             (output-for (id name)
               (or (and name (find name outputs :test #'equal
                                               :key (lambda (entry) (getf entry :name))))
                   (let ((box (and (member id old-ids)
                                   (find id input-layout :key (lambda (entry) (getf entry :id))))))
                     (when (and box (getf box :visible))
                       (let ((x (+ (getf box :x) (/ (getf box :width) 2)))
                             (y (+ (getf box :y) (/ (getf box :height) 2))))
                         (find-if (lambda (entry)
                                    (and (<= (getf entry :x) x)
                                         (< x (+ (getf entry :x) (getf entry :width)))
                                         (<= (getf entry :y) y)
                                         (< y (+ (getf entry :y) (getf entry :height)))))
                                  outputs))))
                   output))
             (arrange ()
               (if (null area)
                   (setf visible nil stack nil)
                   (let* ((tiled (remove-if #'full-box (workspace active)))
                          (x (+ (getf area :x) gap)) (y (+ (getf area :y) gap))
                          (width (- (getf area :width) (* 2 gap)))
                          (height (- (getf area :height) (* 2 gap))))
                     (loop for (id . rest) on tiled do
                       (cond ((null rest) (remember-box id x y width height))
                             ((>= width height)
                              (let ((half (floor (- width gap) 2)))
                                (remember-box id x y half height)
                                (incf x (+ half gap)) (decf width (+ half gap))))
                             (t
                              (let ((half (floor (- height gap) 2)))
                                (remember-box id x y width half)
                                (incf y (+ half gap)) (decf height (+ half gap)))))
                       (show-id id))
                     (dolist (id (workspace active))
                       (when (full-box id) (show-id id) (raise-id id))))))
             (set-fullscreen (id on &optional name)
               (if on
                   (let ((target (output-for id name)))
                     (unless target (return-from set-fullscreen nil))
                     (let ((box (remember-box id (getf target :x) (getf target :y)
                                              (getf target :width) (getf target :height))))
                       (setf full (cons (copy-list box)
                                        (remove id full :key (lambda (entry) (getf entry :id))))))
                     (show-id id)
                     (focus-id id))
                   (setf full (remove id full :key (lambda (entry) (getf entry :id)))))
               (arrange))
             (switch-workspace (number)
               (unless (and (<= 1 number count) (/= number active))
                 (return-from switch-workspace nil))
               (dolist (id (workspace active)) (hide-id id))
               (setf active number)
               (arrange)
               (focus-id (car (last (workspace active)))))
             (move-focused (number)
               (let ((id (current-focus)))
                 (when (and id (<= 1 number count) (/= number active))
                   (setf (nth (1- active) workspaces) (remove id (workspace active)))
                   (hide-id id)
                   (append-window number id)
                   (arrange)
                   (focus-id (car (last (workspace active)))))))
             (cycle-focus (direction)
               (let* ((wins (workspace active))
                      (index (or (position (current-focus) wins) 0)))
                 (when wins (focus-id (nth (mod (+ index direction) (length wins)) wins)))))
             (workspace-command (command prefix)
               (when (and (stringp command) (> (length command) (length prefix))
                          (string= prefix command :end2 (length prefix)))
                 (parse-integer command :start (length prefix) :junk-allowed t))))
      (dolist (id ids)
        (unless (or (member id new-ids) (some (lambda (wins) (member id wins)) workspaces))
          (setf full (remove id full :key (lambda (entry) (getf entry :id))))
          (append-window active id)))
      (unless (and (eq type :key) (equal "wm" (getf event :owner))
                   (equal "fullscreen" (getf event :command)))
        (setf full
              (remove-if (lambda (entry)
                           (let ((resolved (find (getf entry :id) layout
                                                 :key (lambda (window) (getf window :id)))))
                             (when (and resolved (not (getf resolved :fullscreen)))
                               (setf retired-full t))))
                         full)))
      (unless (member focused ids) (setf focused nil))
      (when (or removed retired-full (eq type :mount)
                (not (equal geometry-key (getf state :geometry-key))))
        (loop for wins in workspaces for number from 1
              unless (= number active) do (dolist (id wins) (hide-id id)))
        (arrange))
      (when (and removed (workspace active)) (focus-id (car (last (workspace active)))))
      (dolist (window windows)
        (let ((id (getf window :id)))
          (when (member id new-ids)
            (when (or (getf window :maximize-requested) (getf window :maximize))
              (pushnew id maximized))
            (let* ((props (properties id))
                   (requested-workspace (property props :workspace))
                   (number (and (realp requested-workspace) (floor requested-workspace)))
                   (target (if (and number (<= 1 number count)) number active)))
              (append-window target id)
              (if (/= target active)
                  (hide-id id)
                  (progn
                    (if (or (property props :fullscreen)
                            (and honor (or (getf window :fullscreen-requested)
                                           (getf window :fullscreen))))
                        (set-fullscreen id t
                                        (when (and honor (not (property props :fullscreen)))
                                          (getf window :output)))
                        (arrange))
                    (multiple-value-bind (value present) (property props :focus)
                      (unless (and present (null value)) (focus-id id)))))))))
      (case type
        (:pointer
         (when (and (eq (getf event :state) :enter) (setting snapshot :focus-follows-mouse)
                    (member (getf event :id) visible))
           (setf focused (getf event :id))))
        (:button
         (when (eq :pressed (getf event :state))
           (let ((id (getf event :id)))
             (focus-id (when (member id visible) id)))))
        (:key
         (when (equal "wm" (getf event :owner))
           (let* ((command (getf event :command))
                  (switch (workspace-command command "workspace-"))
                  (move (workspace-command command "move-")))
             (cond (switch (switch-workspace switch))
                   (move (move-focused move))
                   ((equal command "next") (cycle-focus 1))
                   ((equal command "previous") (cycle-focus -1))
                   ((equal command "fullscreen")
                    (let ((id (current-focus)))
                      (when id (set-fullscreen id (null (full-box id))))))))))
        ((:metadata :request)
         (let ((id (getf event :id)) (request (getf event :request)))
           (when (member id ids)
             (case request
               (:fullscreen
                (if (getf event :requested)
                    (when honor (set-fullscreen id t (getf event :output)))
                    (set-fullscreen id nil)))
               (:unfullscreen (set-fullscreen id nil))
               (:maximize
                (if (getf event :requested)
                    (pushnew id maximized)
                    (setf maximized (remove id maximized))))
               (:unmaximize (setf maximized (remove id maximized)))
               (:close (push (close-window id) commands))
               (:activate
                (loop for wins in workspaces for number from 1
                      when (member id wins) do (switch-workspace number) (return))
                (focus-id id)))))))
      (let ((effects nil))
        (dolist (id ids)
          (let ((box (or (full-box id) (window-box id)))
                (shown (and area (member id visible) t)))
            (when box
              (push (place id (getf box :x) (getf box :y)
                           (getf box :width) (getf box :height) shown) effects))
            (push (if shown (show-window id) (hide-window id)) effects)
            (push (fullscreen id (not (null (full-box id)))) effects)
            (push (maximize id (not (null (member id maximized)))) effects)))
        (dolist (id stack) (when (member id visible) (push (raise-window id) effects)))
        (push (focus (when (member focused visible) focused) :raise nil) effects)
        (dolist (binding '(("j" :next) ("Tab" :next) ("k" :previous) ("f" :fullscreen)))
          (push (bind-key '(:super) (first binding) (second binding)) effects))
        (loop for number from 1 to (min count 9)
              for switch in '(:workspace-1 :workspace-2 :workspace-3 :workspace-4 :workspace-5
                              :workspace-6 :workspace-7 :workspace-8 :workspace-9)
              for move in '(:move-1 :move-2 :move-3 :move-4 :move-5 :move-6 :move-7 :move-8 :move-9)
              do
          (push (bind-key '(:super) (princ-to-string number)
                          switch) effects)
          (push (bind-key '(:super :shift) (princ-to-string number)
                          move) effects))
        (push (publish-state :wm-state
                             (list :active active :workspaces
                                   (loop for wins in workspaces for number from 1
                                         collect (list :id number :windows (length wins)))))
              effects)
        (let ((value (json-object
                      (cons "active" active)
                      (cons "workspaces"
                            (apply #'json-array
                                   (loop for wins in workspaces for number from 1
                                         collect (json-object (cons "id" number)
                                                              (cons "windows" (length wins)))))))))
          (push (serve-state "wm_state" value) effects)
          (push (announce "wm_state" value) effects))
        (values (list :active active :workspaces workspaces :fullscreen full :maximized maximized
                      :focused focused :ids ids :boxes boxes :stacking stack
                      :visible visible :geometry-key geometry-key)
                (nreverse effects) commands)))))

(define-extension "drag" (:reads (:windows :layout :button :grab) :state nil) (snapshot state event)
  (labels ((drag-box (state dx dy)
             (flet ((bound (value) (min 1048576 (max -1048576 value)))
                    (size (value) (min 16384 (max 64 value))))
               (if (eq (getf state :mode) :move)
                   (list (bound (+ (getf state :base-x) dx))
                         (bound (+ (getf state :base-y) dy))
                         (getf state :base-width) (getf state :base-height))
                   (list (getf state :base-x) (getf state :base-y)
                         (size (+ (getf state :base-width) dx))
                         (size (+ (getf state :base-height) dy)))))))
  (let* ((layout (context snapshot :layout))
         (windows (context snapshot :windows))
         (ids (loop for window in windows
                    when (getf window :buffered t) collect (getf window :id)))
         (type (getf event :type))
         (id (getf state :id))
         (generation (getf state :buffer-generation))
         (modifiers (getf event :modifiers))
         (target (find (getf event :id) layout :key (lambda (window) (getf window :id)))))
    (cond
      ((and state (or (not (member id ids))
                      (not (eql generation
                                (getf (find id windows :key (lambda (w) (getf w :id)))
                                      :buffer-generation)))))
       (values nil nil nil))
      ((and (eq type :button) (eq (getf event :state) :pressed) target
            (member (getf event :id) ids) (member (getf event :button) '(272 273))
            (integerp modifiers) (logtest 64 modifiers))
       (let* ((window-id (getf event :id))
             (buffer-generation (getf (find window-id windows :key (lambda (w) (getf w :id)))
                                      :buffer-generation))
             (mode (if (eql (getf event :button) 272) :move :resize))
             (box (list (getf target :x) (getf target :y)
                        (getf target :width) (getf target :height))))
         (values (list :id window-id :mode mode :buffer-generation buffer-generation
                       :origin-x (getf event :x) :origin-y (getf event :y)
                       :base-x (first box) :base-y (second box)
                       :base-width (third box) :base-height (fourth box)
                       :x (first box) :y (second box) :width (third box) :height (fourth box))
                 (list (grab window-id mode :buffer-generation buffer-generation) (apply #'place window-id box)
                       (fullscreen window-id nil))
                 nil)))
      ((and (eq type :button) (eq (getf event :state) :released) state (eql (getf event :id) id))
       (values nil nil nil))
      ((and (eq type :grab) state (eql (getf event :id) id))
       (let* ((dx (- (getf event :x) (getf state :origin-x)))
              (dy (- (getf event :y) (getf state :origin-y)))
              (box (drag-box state dx dy)))
         (values (list :id id :mode (getf state :mode) :buffer-generation generation
                       :origin-x (getf state :origin-x) :origin-y (getf state :origin-y)
                       :base-x (getf state :base-x) :base-y (getf state :base-y)
                       :base-width (getf state :base-width) :base-height (getf state :base-height)
                       :x (first box) :y (second box) :width (third box) :height (fourth box))
                 (list (grab id (getf state :mode) :buffer-generation generation) (apply #'place id box)
                       (fullscreen id nil))
                 nil)))
      (state
       (values state
               (list (grab id (getf state :mode) :buffer-generation generation)
                     (place id (getf state :x) (getf state :y)
                            (getf state :width) (getf state :height) t)
                     (fullscreen id nil))
               nil))
      (t (values nil nil nil))))))

(define-extension "commands" (:reads (:key :focus) :state nil) (snapshot state event)
  (declare (ignore state))
  (let ((focused (context snapshot :focus))
        (command (when (and (eq (getf event :type) :key) (equal (getf event :owner) "commands"))
                   (getf event :command))))
    (values nil
            (list (bind-key '(:super) "Return" :terminal)
                  (bind-key '(:super) "q" :close)
                  (bind-key '(:super) "d" :launcher)
                  (bind-key '(:super :shift) "e" :quit)
                  (bind-key '(:super :shift) "r" :reload)
                  (bind-key '(:super :shift) "Escape" :quit))
            (cond ((equal command "terminal") (list (launch "foot")))
                  ((equal command "launcher") (list (launch "fuzzel")))
                  ((and (equal command "close") focused) (list (close-window focused)))
                  ((equal command "reload") (list (reload)))
                  ((equal command "quit") (list (quit)))))))

(define-extension "notification-popups" (:reads (:services :outputs) :state nil)
    (snapshot state event)
  (declare (ignore state event))
  (let* ((service (service-state snapshot :notifications))
         (notifications (and (getf service :available)
                             (getf service :notifications)))
         (outputs (context snapshot :outputs))
         (estimates
           (loop for output in outputs collect
             (let* ((scale (max 1 (getf output :scale-120 120)))
                    (width (ceiling (* 320 scale) 120))
                    (summary-height (ceiling (* 91 scale) 600))
                    (body-height (ceiling (* 78 scale) 600))
                    (padding (ceiling (* 20 scale) 120))
                    (inner-gap (ceiling (* 4 scale) 120))
                    (stack-gap (ceiling (* 8 scale) 120))
                    (height (+ (* 2 summary-height) (* 8 body-height)
                               padding inner-gap stack-gap)))
               (list :area (* width height)))))
         (per-surface-limit
           (or (loop for estimate in estimates
                     minimize (floor (* 16 1024 1024) (getf estimate :area)))
               64))
         (aggregate-area (loop for estimate in estimates sum (getf estimate :area)))
         (aggregate-limit (if (plusp aggregate-area)
                              (floor (* 32 1024 1024) aggregate-area)
                              64))
         (summary-lines 2)
         (body-lines 8)
         (visible-nodes-per-card (+ 1 1 summary-lines 1 body-lines))
         (ui-card-limit (floor (1- 512) visible-nodes-per-card))
         (copy-nodes-per-card 512)
         (copy-card-limit
           (floor 32768 (* (max 1 (length outputs)) copy-nodes-per-card)))
         (card-limit (max 0 (min 64 per-surface-limit aggregate-limit
                                    ui-card-limit copy-card-limit))))
    (labels ((preview-lines (value line-limit character-limit)
               (let* ((end (min (length value) character-limit))
                      (limit (max 1 line-limit))
                      (start 0)
                      (lines nil))
                 (loop for index below end
                       when (char= (char value index) #\Newline)
                         do (push (subseq value start index) lines)
                            (setf start (1+ index))
                            (when (= (length lines) limit)
                              (return)))
                 (when (< (length lines) limit)
                   (push (subseq value start end) lines))
                 (nreverse lines)))
             (text (value size color)
               (ui :text :text value :size size :color color))
             (text-block (value line-limit character-limit size color)
               (let ((lines (preview-lines value line-limit character-limit)))
                 (if (= 1 (length lines))
                     (list (text (first lines) size color))
                     (list (ui :column :gap 0
                               :children (mapcar (lambda (line) (text line size color))
                                                  lines))))))
             (card (notification)
               (let* ((app (getf notification :app))
                      (summary (getf notification :summary))
                      (body (getf notification :body))
                      (urgent (getf notification :urgent)))
                 (ui :column :width 320 :padding 10 :gap 4 :radius 8
                     :background (if urgent "#45222c" "#1e1e2e")
                     :children
                     (append
                      (text-block (if (plusp (length summary)) summary app)
                                  summary-lines 256 14 "#cdd6f4")
                      (when (plusp (length body))
                        (text-block body body-lines 512 12 "#a6adc8")))))))
      (values nil
              (when (and (listp notifications) notifications (plusp card-limit))
                (list
                 (shell-surface :notifications
                   (ui :column :gap 8
                       :children (loop for notification in notifications
                                        for count from 1 to card-limit
                                        collect (card notification)))
                   :anchors '(:top :right) :margin 8 :layer :top
                   :exclusive-zone 0 :background "#00000000")))
              nil))))
