(in-package #:tomoe-user)

(defparameter +special-bindings+ '(("grave" :term))
  "(KEY NAME) pairs: Mod+KEY toggles special NAME, Mod+Shift+KEY parks the focused window in it.")

(define-extension "special" (:reads (:windows :rules :outputs :workareas :focus :key :button) :state nil)
    (snapshot state event)
  (let* ((ids (mapcar (lambda (window) (getf window :id)) (context snapshot :windows)))
         (known (getf state :ids))
         (spaces (loop for (name . space) in (getf state :spaces)
                       collect (list name :shown (getf space :shown)
                                      :windows (remove-if-not (lambda (id) (member id ids))
                                                              (getf space :windows)))))
         (output (first (context snapshot :outputs)))
         (area (or (find (getf output :name) (context snapshot :workareas)
                         :test #'equal :key (lambda (entry) (getf entry :name)))
                   output))
         (focused (getf state :focused))
         (command (and (eq (getf event :type) :key) (equal (getf event :owner) "special")
                       (getf event :command))))
    (labels ((space (name)
               (or (assoc name spaces)
                   (car (push (list name :shown nil :windows nil) spaces))))
             (present (space)
               (setf focused (car (last (getf (rest space) :windows)))))
             (park (name id)
               (unless (some (lambda (space) (member id (getf (rest space) :windows))) spaces)
                 (let ((space (space name)))
                   (setf (getf (rest space) :windows) (append (getf (rest space) :windows) (list id)))
                   (if (getf (rest space) :shown) (present space) (setf focused nil))))))
      (dolist (id (set-difference ids known))
        (let* ((rules (rules-for snapshot id))
               (name (cdr (or (assoc :special rules) (assoc "special" rules :test #'equal)))))
          (when (stringp name) (park (intern (string-upcase name) :keyword) id))))
      (loop for (key name) in +special-bindings+
            for toggle = (format nil "toggle-~(~A~)" name)
            for move = (format nil "move-~(~A~)" name)
            do (cond ((equal command toggle)
                      (let ((space (space name)))
                        (setf (getf (rest space) :shown) (not (getf (rest space) :shown)))
                        (if (getf (rest space) :shown) (present space) (setf focused nil))))
                     ((and (equal command move) (member (context snapshot :focus) ids))
                      (park name (context snapshot :focus)))))
      (when (eq (getf event :type) :button)
        (when (eq (getf event :state) :pressed)
          (setf focused (find (getf event :id)
                              (loop for space in spaces when (getf (rest space) :shown)
                                    append (getf (rest space) :windows))))))
      (unless (member focused ids) (setf focused nil))
      (let ((effects nil))
        (dolist (space spaces)
          (destructuring-bind (&key shown windows) (rest space)
            (dolist (id windows)
              (if (and shown area)
                  (let ((width (floor (* (getf area :width) 3) 4))
                        (height (floor (* (getf area :height) 3) 4)))
                    (push (place id (+ (getf area :x) (floor (- (getf area :width) width) 2))
                                 (+ (getf area :y) (floor (- (getf area :height) height) 2))
                                 width height)
                          effects)
                    (push (raise-window id) effects))
                  (push (hide-window id) effects)))))
        (when focused (push (focus focused) effects))
        (push (publish-state :wm-exclude
                             (loop for space in spaces append (getf (rest space) :windows)))
              effects)
        (loop for (key name) in +special-bindings+
              do (push (bind-key '(:mod) key (intern (format nil "TOGGLE-~A" name) :keyword)) effects)
                 (push (bind-key '(:mod :shift) key (intern (format nil "MOVE-~A" name) :keyword))
                       effects))
        (values (list :ids ids :spaces spaces :focused focused) (nreverse effects) nil)))))
