(in-package #:tomoe-user)

(defparameter +zoomer-defaults+
  '(:planes 4 :zoom-step 1.2 :pan-step 160 :open-size 0.6 :min-size 64 :cascade 32))

(defun zoomer--visible (area view)
  "The world rectangle (X Y WIDTH HEIGHT) seen through VIEW over AREA."
  (destructuring-bind (vx vy zoom) view
    (list (+ (/ (getf area :x) zoom) vx) (+ (/ (getf area :y) zoom) vy)
          (/ (getf area :width) zoom) (/ (getf area :height) zoom))))

(defun zoomer--zoom-around (view factor wx wy sx sy)
  "VIEW zoomed by FACTOR keeping world point WX WY at screen point SX SY."
  (let ((zoom (max 1/16 (min 16 (* (third view) factor)))))
    (list (round (- wx (/ sx zoom))) (round (- wy (/ sy zoom))) zoom)))

(defun zoomer--edges (edges)
  "The (LEFT RIGHT TOP BOTTOM) flags of a resize edge keyword."
  (let ((name (if (member edges '(nil :none)) "bottom-right" (string-downcase edges))))
    (mapcar (lambda (side) (and (search side name) t)) '("left" "right" "top" "bottom"))))

(define-extension "zoomer"
    (:reads (:windows :layout :outputs :workareas :focus :key :button :grab :request :data)
     :state nil)
    (snapshot state event)
  (let* ((options (append (state-value snapshot :zoomer-settings) +zoomer-defaults+))
         (step (getf options :zoom-step))
         (pan-step (getf options :pan-step))
         (min-size (getf options :min-size))
         (windows (context snapshot :windows))
         (ids (mapcar (lambda (window) (getf window :id)) windows))
         (layout (context snapshot :layout))
         (output (first (context snapshot :outputs)))
         (area (or (find (getf output :name) (context snapshot :workareas)
                         :test #'equal :key (lambda (entry) (getf entry :name)))
                   output))
         (planes (or (loop for plane in (getf state :planes)
                           collect (list :view (getf plane :view)
                                         :wins (remove-if-not (lambda (id) (member id ids))
                                                              (getf plane :wins))))
                     (loop repeat (max 1 (getf options :planes))
                           collect (list :view (list 0 0 1) :wins nil))))
         (current (min (getf state :current 0) (1- (length planes))))
         (cascade (getf state :cascade 0))
         (boxes (remove-if-not (lambda (entry) (member (first entry) ids)) (getf state :boxes)))
         (fit (remove-if-not (lambda (entry) (member (first entry) ids)) (getf state :fit)))
         (drag (and (member (getf (getf state :drag) :id) (cons 0 ids)) (getf state :drag)))
         (focused (getf state :focused))
         (type (getf event :type))
         (command (and (eq type :key) (equal (getf event :owner) "zoomer") (getf event :command))))
    (labels ((plane (index) (nth index planes))
             (wins () (getf (plane current) :wins))
             (view () (getf (plane current) :view))
             (set-camera (view) (setf (getf (nth current planes) :view) view))
             (set-wins (index wins) (setf (getf (nth index planes) :wins) wins))
             (box (id)
               (or (rest (assoc id boxes))
                   (let ((resolved (find id layout :key (lambda (w) (getf w :id)))))
                     (when resolved
                       (list (getf resolved :x) (getf resolved :y)
                             (getf resolved :width) (getf resolved :height))))))
             (remember (id box) (setf boxes (acons id box (remove id boxes :key #'first))))
             (to-top (id)
               (loop for plane in planes for index from 0
                     when (member id (getf plane :wins))
                       do (set-wins index (append (remove id (getf plane :wins)) (list id)))))
             (focus-top () (setf focused (car (last (wins)))))
             (visible () (and area (zoomer--visible area (view))))
             (switch-plane (index)
               (when (and (/= index current) (< -1 index (length planes)))
                 (setf current index)
                 (focus-top)))
             (pan (dx dy)
               (destructuring-bind (x y zoom) (view)
                 (set-camera (list (+ x (round dx zoom)) (+ y (round dy zoom)) zoom))))
             (zoom-center (factor)
               (when area
                 (destructuring-bind (x y zoom) (view)
                   (let ((sx (+ (getf area :x) (/ (getf area :width) 2)))
                         (sy (+ (getf area :y) (/ (getf area :height) 2))))
                     (set-camera (zoomer--zoom-around (view) factor (+ (/ sx zoom) x) (+ (/ sy zoom) y)
                                                      sx sy))))))
             (begin (id mode &optional edges)
               (let ((box (box id)))
                 (when box
                   (to-top id)
                   (setf focused id
                         drag (list :id id :mode mode :box box :edges (zoomer--edges edges)
                                    :dx 0 :dy 0)))))
             (toggle-fit ()
               (let ((saved (rest (assoc focused fit))))
                 (cond (saved (setf fit (remove focused fit :key #'first))
                              (remember focused saved))
                       ((and focused (box focused) (visible))
                        (setf fit (acons focused (box focused) fit))
                        (remember focused (mapcar #'round (visible)))
                        (to-top focused))))))
      (dolist (id (set-difference ids (loop for plane in planes append (getf plane :wins))))
        (set-wins current (append (wins) (list id)))
        (if (or (null (getf state :planes)) (not (visible)))
          (when (box id) (remember id (box id)))
          (destructuring-bind (x y width height) (visible)
            (let ((w (max min-size (round (* width (getf options :open-size)))))
                  (h (max min-size (round (* height (getf options :open-size)))))
                  (offset (* cascade (getf options :cascade))))
              (remember id (list (+ (round (+ x (/ (- width w) 2))) offset)
                                 (+ (round (+ y (/ (- height h) 2))) offset) w h))
              (setf cascade (mod (1+ cascade) 5)))))
        (setf focused id))
      (unless (member focused (wins)) (focus-top))
      (let ((resolved (context snapshot :focus)))
        (when (and (member resolved (wins)) (not (eql resolved (previous-context snapshot :focus))))
          (setf focused resolved)))
      (case type
        (:button
         (cond ((and drag (eq (getf event :state) :released)) (setf drag nil))
               ((and (eq (getf event :state) :pressed) (member (getf event :id) (wins)))
                (setf focused (getf event :id)))))
        (:grab
         (when (and drag (eql (getf event :id) (getf drag :id)))
           (let ((dx (+ (getf drag :dx) (getf event :dx))) (dy (+ (getf drag :dy) (getf event :dy))))
             (setf (getf drag :dx) dx (getf drag :dy) dy)
             (destructuring-bind (x y width height) (getf drag :box)
               (ecase (getf drag :mode)
                 (:move (remember (getf drag :id) (list (+ x dx) (+ y dy) width height)))
                 (:resize
                  (destructuring-bind (left right top bottom) (getf drag :edges)
                    (let ((w (max min-size (cond (left (- width dx)) (right (+ width dx)) (t width))))
                          (h (max min-size (cond (top (- height dy)) (bottom (+ height dy)) (t height)))))
                      (remember (getf drag :id)
                                (list (if left (- (+ x width) w) x) (if top (- (+ y height) h) y) w h)))))
                 (:pointer
                  (destructuring-bind (vx vy zoom) (view)
                    (declare (ignore vx vy))
                    (set-camera (list (- x dx) (- y dy) zoom)))))))))
        (:request
         (let ((id (getf event :id)))
           (when (member id (wins))
             (case (getf event :request)
               (:move (begin id :move))
               (:resize (begin id :resize (getf event :edges)))))))
        (:key
         (let ((plane-number (and command (> (length command) 6) (string= "plane-" command :end2 6)
                                  (parse-integer command :start 6 :junk-allowed t))))
           (cond
             (plane-number (switch-plane (1- plane-number)))
             ((equal command "next-plane") (switch-plane (mod (1+ current) (length planes))))
             ((equal command "previous-plane") (switch-plane (mod (1- current) (length planes))))
             ((equal command "zoom-in") (zoom-center step))
             ((equal command "zoom-out") (zoom-center (/ step)))
             ((equal command "reset-view") (set-camera (list 0 0 1)))
             ((equal command "fit") (toggle-fit))
             ((equal command "pan-left") (pan (- pan-step) 0))
             ((equal command "pan-right") (pan pan-step 0))
             ((equal command "pan-up") (pan 0 (- pan-step)))
             ((equal command "pan-down") (pan 0 pan-step))
             ((equal command "drag-end") (setf drag nil))
             ((member command '("zoom-scroll-in" "zoom-scroll-out") :test #'equal)
              (set-camera (zoomer--zoom-around (view) (if (equal command "zoom-scroll-in") step (/ step))
                                               (getf event :x) (getf event :y)
                                               (getf event :sx) (getf event :sy))))
             ((equal command "move") (when (member (getf event :window) (wins))
                                       (begin (getf event :window) :move)))
             ((equal command "resize") (when (member (getf event :window) (wins))
                                         (begin (getf event :window) :resize)))
             ((equal command "pan")
              (destructuring-bind (x y zoom) (view)
                (declare (ignore zoom))
                (setf drag (list :id 0 :mode :pointer :box (list x y 0 0) :dx 0 :dy 0))))))))
      (when (member focused (wins)) (to-top focused))
      (let ((effects nil))
        (flet ((emit (effect) (push effect effects)))
          (loop for plane in planes for index from 0
                do (dolist (id (getf plane :wins))
                     (let ((box (box id)) (shown (= index current)))
                       (if box
                           (emit (apply #'place id (append box (list shown))))
                           (emit (if shown (show-window id) (hide-window id))))
                       (when shown (emit (raise-window id))))))
          (emit (apply #'set-view (view)))
          (emit (focus (when (member focused (wins)) focused)))
          (when drag
            (emit (if (eq (getf drag :mode) :pointer)
                      (grab nil :pointer)
                      (grab (getf drag :id) (getf drag :mode)))))
          (emit (bind-button '(:mod) :left :move :release :drag-end))
          (emit (bind-button '(:mod) :right :resize :release :drag-end))
          (emit (bind-button '(:mod) :middle :pan :release :drag-end))
          (emit (bind-scroll '(:mod) :up :zoom-scroll-in))
          (emit (bind-scroll '(:mod) :down :zoom-scroll-out))
          (emit (bind-key '(:mod) "Tab" :next-plane :description "next plane"))
          (emit (bind-key '(:mod :shift) "Tab" :previous-plane :description "previous plane"))
          (loop for number from 1 to (min 9 (length planes))
                do (emit (bind-key '(:mod) (princ-to-string number)
                                   (intern (format nil "PLANE-~D" number) :keyword))))
          (emit (bind-key '(:mod) "equal" :zoom-in :description "zoom in"))
          (emit (bind-key '(:mod) "minus" :zoom-out :description "zoom out"))
          (emit (bind-key '(:mod) "period" :reset-view :description "reset view"))
          (emit (bind-key '(:mod) "f" :fit :description "fit window to view"))
          (emit (bind-key '(:mod) "Left" :pan-left))
          (emit (bind-key '(:mod) "Right" :pan-right))
          (emit (bind-key '(:mod) "Up" :pan-up))
          (emit (bind-key '(:mod) "Down" :pan-down)))
        (values (list :planes planes :current current :cascade cascade :boxes boxes :fit fit
                      :drag drag :focused focused)
                (nreverse effects) nil)))))
