(in-package #:tomoe)


(defconstant +json-false+ :json-false)
(defconstant +json-max-text+ 1048576)
(defconstant +json-max-string+ 65536)
(defconstant +json-max-depth+ 64)
(defconstant +json-max-nodes+ 32768)
(defconstant +json-max-number-lexeme+ 256)

(defun %json-ratio-p (value)
  (and (rationalp value) (not (integerp value))))

(defun %json-finite-float-p (value)
  (and (floatp value)
       (not (sb-ext:float-nan-p value))
       (not (sb-ext:float-infinity-p value))))

(defun %json-finite-real-p (value)
  (and (realp value)
       (or (not (floatp value)) (%json-finite-float-p value))))

(defun %json-number-in-range-p (value)
  (and (integerp value)
       (<= (- (expt 2 63)) value (1- (expt 2 64)))))

(defun %json-check-string (value)
  (check-type value string)
  (when (> (length value) +json-max-string+)
    (error "JSON string exceeds ~D characters." +json-max-string+))
  (loop for character across value
        for code = (char-code character)
        when (or (> code #x10ffff) (and (<= #xd800 code) (<= code #xdfff)))
          do (error "JSON strings must contain Unicode scalar values."))
  value)

(defun %json-container-payload (value marker)
  (and (consp value)
       (eq (car value) marker)
       (consp (cdr value))
       (null (cddr value))
       (second value)))

(defun %json-circular-p (list)
  "True when the conses of LIST loop back on themselves."
  (loop for slow = list then (cdr slow)
        for fast = (and (consp list) (cdr list)) then (and (consp (cdr fast)) (cddr fast))
        while (and (consp slow) (consp fast))
        thereis (eq slow fast)))

(defun %json-validate-value (value)
  "Validate VALUE as the JSON subset and reject cycles before copying it.
The containers being visited ride a stack-allocated path, so validating
allocates nothing."
  (let ((nodes 0))
    (labels ((node (item depth path)
               (when (> depth +json-max-depth+)
                 (error "JSON nesting exceeds ~D levels." +json-max-depth+))
               (when (> (incf nodes) +json-max-nodes+)
                 (error "JSON value exceeds ~D nodes." +json-max-nodes+))
               (cond
                 ((null item) nil)
                 ((eq item t) nil)
                 ((eq item +json-false+) nil)
                 ((stringp item) (%json-check-string item))
                 ((integerp item)
                  (unless (%json-number-in-range-p item)
                    (error "JSON integer is outside the data range.")))
                 ((%json-ratio-p item)
                  (unless (and (<= (- (expt 2 63)) (numerator item) (1- (expt 2 64)))
                               (<= 1 (denominator item) (1- (expt 2 64)))
                               (%json-finite-real-p (coerce item 'double-float)))
                    (error "JSON rational is outside the finite data range.")))
                 ((floatp item)
                  (unless (%json-finite-float-p item)
                    (error "JSON numbers must be finite.")))
                 ((and (consp item) (eq (car item) :json-object))
                  (when (member item path :test #'eq)
                    (error "Cyclic JSON object."))
                  (unless (and (consp (cdr item)) (null (cddr item)))
                    (error "Malformed JSON object container."))
                  (when (%json-circular-p (second item))
                    (error "Cyclic JSON object member list."))
                  (let ((path (cons item path)) (tail (second item)))
                    (declare (dynamic-extent path))
                    (loop while (consp tail) do
                      (let ((entry (car tail)))
                        (unless (and (consp entry) (stringp (car entry)))
                          (error "JSON object members need string keys."))
                        (%json-check-string (car entry))
                        (node (cdr entry) (1+ depth) path))
                      (setf tail (cdr tail)))
                    (unless (null tail)
                      (error "JSON object members must form a proper list."))))
                 ((and (consp item) (eq (car item) :json-array))
                  (when (member item path :test #'eq)
                    (error "Cyclic JSON array."))
                  (unless (and (consp (cdr item)) (null (cddr item)))
                    (error "Malformed JSON array container."))
                  (when (%json-circular-p (second item))
                    (error "Cyclic JSON array member list."))
                  (let ((path (cons item path)) (tail (second item)))
                    (declare (dynamic-extent path))
                    (loop while (consp tail) do
                      (node (car tail) (1+ depth) path)
                      (setf tail (cdr tail)))
                    (unless (null tail)
                      (error "JSON array members must form a proper list."))))
                 (t (error "Value of type ~A is not JSON data." (type-of item))))))
      (node value 1 nil)
      value)))

(defun %json-utf8-width (character)
  "Return the UTF-8 byte width of one Unicode scalar character."
  (let ((code (char-code character)))
    (cond ((<= code #x7f) 1)
          ((<= code #x7ff) 2)
          ((<= code #xffff) 3)
          (t 4))))

(defun %json-bounded-size-add (size amount)
  (let ((result (+ size amount)))
    (when (> result +json-max-text+)
      (error "JSON text exceeds ~D UTF-8 bytes." +json-max-text+))
    result))

(defun %json-text-size (text)
  "Count TEXT's UTF-8 bytes without allocating an octet copy."
  (let ((size 0))
    (loop for character across text do
      (setf size (%json-bounded-size-add size (%json-utf8-width character))))
    size))

(defun %json-string-output-size (value)
  (let ((size 2))
    (loop for character across value do
      (setf size
            (%json-bounded-size-add
             size
             (case character
               ((#\" #\\ #\Backspace #\Page #\Newline #\Return #\Tab) 2)
               (t (if (< (char-code character) #x20)
                      6
                      (%json-utf8-width character)))))))
    size))

(defun %json-output-size (value depth pretty)
  "Preflight the serialized size before WITH-OUTPUT-TO-STRING allocates it."
  (cond
    ((null value) 4)
    ((eq value t) 4)
    ((eq value +json-false+) 5)
    ((stringp value) (%json-string-output-size value))
    ((or (integerp value) (%json-ratio-p value) (floatp value))
     (length (%json-format-number value)))
    ((and (consp value) (eq (car value) :json-array))
     (let ((size 1)
           (values (second value)))
       (unless (null values)
         (when pretty (setf size (%json-bounded-size-add size 1)))
         (loop for tail on values do
           (when pretty
             (setf size (%json-bounded-size-add size (* 2 (1+ depth)))))
           (setf size (%json-bounded-size-add
                       size (%json-output-size (car tail) (1+ depth) pretty)))
           (when (cdr tail)
             (setf size (%json-bounded-size-add size 1))
             (when pretty (setf size (%json-bounded-size-add size 1)))))
         (when pretty
           (setf size (%json-bounded-size-add size 1))
           (setf size (%json-bounded-size-add size (* 2 depth)))))
       (%json-bounded-size-add size 1)))
    ((and (consp value) (eq (car value) :json-object))
     (let ((size 1)
           (members (second value)))
       (unless (null members)
         (when pretty (setf size (%json-bounded-size-add size 1)))
         (loop for tail on members do
           (when pretty
             (setf size (%json-bounded-size-add size (* 2 (1+ depth)))))
           (setf size (%json-bounded-size-add
                       size (%json-string-output-size (caar tail))))
           (setf size (%json-bounded-size-add size (if pretty 2 1)))
           (setf size (%json-bounded-size-add
                       size (%json-output-size (cdar tail) (1+ depth) pretty)))
           (when (cdr tail)
             (setf size (%json-bounded-size-add size 1))
             (when pretty (setf size (%json-bounded-size-add size 1)))))
         (when pretty
           (setf size (%json-bounded-size-add size 1))
           (setf size (%json-bounded-size-add size (* 2 depth)))))
       (%json-bounded-size-add size 1)))
    (t (error "Value of type ~A is not JSON data." (type-of value)))))

(defun %json-copy-value (value)
  (%json-validate-value value)
  (%json-output-size value 0 nil)
  (copy-data value))

(defun json-object (&rest pairs)
  "Construct a JSON object from cons pairs or alternating key/value values.
Duplicate keys are replaced by their last value, like serde_json::Value."
  (when (and pairs (every #'consp pairs))
    (setf pairs (mapcan (lambda (pair) (list (car pair) (cdr pair))) pairs)))
  (when (oddp (length pairs))
    (error "JSON object needs alternating key/value arguments."))
  (let ((members nil)
        (seen (make-hash-table :test #'equal)))
    (loop for tail = pairs then (cddr tail) while tail do
      (let ((key (car tail)) (value (second tail)))
        (check-type key string)
        (%json-check-string key)
        (multiple-value-bind (entry presentp) (gethash key seen)
          (if presentp
              (setf (cdr entry) value)
              (let ((entry (cons (copy-seq key) value)))
                (setf (gethash key seen) entry)
                (push entry members))))))
    (%json-copy-value (list :json-object (nreverse members)))))

(defun json-array (&rest values)
  "Construct a JSON array, preserving NIL as an array element only through
  the explicit :JSON-ARRAY container."
  (%json-copy-value (list :json-array values)))

(defun %json-object-members (object)
  (unless (and (consp object) (eq (car object) :json-object)
               (consp (cdr object)) (null (cddr object)))
    (error "Expected a JSON object."))
  (%json-validate-value object)
  (second object))

(defun json-get (object string-key &optional default)
  "Return the last value associated with STRING-KEY in OBJECT."
  (check-type string-key string)
  (%json-check-string string-key)
  (let ((value default) (found-p nil))
    (dolist (entry (%json-object-members object))
      (when (string= string-key (car entry))
        (setf value (cdr entry) found-p t)))
    (if found-p (copy-data value) default)))

(defstruct (%json-parser (:constructor %make-json-parser (text reject-duplicate-keys)))
  text (position 0) (nodes 0) (reject-duplicate-keys nil))

(defun %json-parser-eof-p (parser)
  (= (%json-parser-position parser) (length (%json-parser-text parser))))

(defun %json-parser-peek (parser)
  (unless (%json-parser-eof-p parser)
    (char (%json-parser-text parser) (%json-parser-position parser))))

(defun %json-parser-take (parser)
  (let ((character (%json-parser-peek parser)))
    (unless character (error "Unexpected end of JSON input."))
    (incf (%json-parser-position parser))
    character))

(defun %json-skip-whitespace (parser)
  (loop for character = (%json-parser-peek parser)
        while (and character
                    (member character '(#\Space #\Tab #\Newline #\Return)
                            :test #'char=))
        do (incf (%json-parser-position parser))))

(defun %json-expect (parser character)
  (unless (eql (%json-parser-take parser) character)
    (error "Expected ~C in JSON input." character)))

(defun %json-node (parser depth)
  (when (> depth +json-max-depth+)
    (error "JSON nesting exceeds ~D levels." +json-max-depth+))
  (when (> (incf (%json-parser-nodes parser)) +json-max-nodes+)
    (error "JSON value exceeds ~D nodes." +json-max-nodes+)))

(defun %json-hex-value (character)
  (cond ((and (char>= character #\0) (char<= character #\9))
         (- (char-code character) (char-code #\0)))
        ((and (char>= character #\a) (char<= character #\f))
         (+ 10 (- (char-code character) (char-code #\a))))
        ((and (char>= character #\A) (char<= character #\F))
         (+ 10 (- (char-code character) (char-code #\A))))
        (t nil)))

(defun %json-append-character (buffer character &optional escaped-p)
  (let ((code (char-code character)))
    (when (and (<= #x00 code) (<= code #x1f) (not escaped-p))
      (error "Unescaped control character in JSON string."))
    (when (and (<= #xd800 code) (<= code #xdfff))
      (error "JSON strings must contain Unicode scalar values.")))
  (when (>= (fill-pointer buffer) +json-max-string+)
    (error "JSON string exceeds ~D characters." +json-max-string+))
  (vector-push-extend character buffer)
  buffer)

(defun %json-read-u4 (parser)
  (let ((value 0))
    (dotimes (ignored 4 value)
      (declare (ignorable ignored))
      (let ((digit (%json-hex-value (%json-parser-take parser))))
        (unless digit (error "Invalid Unicode escape in JSON string."))
        (setf value (+ (* value 16) digit))))))

(defun %json-read-escape (parser buffer)
  (let ((escape (%json-parser-take parser)))
    (case escape
      (#\" (%json-append-character buffer #\" t))
      (#\\ (%json-append-character buffer #\\ t))
      (#\/ (%json-append-character buffer #\/ t))
      (#\b (%json-append-character buffer #\Backspace t))
      (#\f (%json-append-character buffer #\Page t))
      (#\n (%json-append-character buffer #\Newline t))
      (#\r (%json-append-character buffer #\Return t))
      (#\t (%json-append-character buffer #\Tab t))
      (#\u
       (let ((code (%json-read-u4 parser)))
         (cond
           ((and (<= #xd800 code) (<= code #xdbff))
            (%json-expect parser #\\)
            (unless (eql (%json-parser-take parser) #\u)
              (error "High surrogate is not followed by a low surrogate."))
            (let ((low (%json-read-u4 parser)))
              (unless (and (<= #xdc00 low) (<= low #xdfff))
                (error "Invalid low surrogate in JSON string."))
              (%json-append-character
               buffer
               (or (code-char (+ #x10000
                                 (* (- code #xd800) #x400)
                                 (- low #xdc00)))
                   (error "Invalid Unicode scalar value."))
               t)))
           ((and (<= #xdc00 code) (<= code #xdfff))
            (error "Unpaired low surrogate in JSON string."))
           (t
            (%json-append-character
             buffer
             (or (code-char code)
                 (error "Invalid Unicode scalar value."))
             t)))))
      (t (error "Unknown JSON string escape ~C." escape)))))

(defun %json-parse-string (parser)
  (%json-expect parser #\")
  (let ((buffer (make-array 64 :element-type 'character :adjustable t :fill-pointer 0)))
    (loop
      (when (%json-parser-eof-p parser)
        (error "Unterminated JSON string."))
      (let ((character (%json-parser-take parser)))
        (cond
          ((eql character #\") (return (coerce buffer 'string)))
          ((eql character #\\) (%json-read-escape parser buffer))
          ((<= (char-code character) #x1f)
           (error "Unescaped control character in JSON string."))
          ((and (<= #xd800 (char-code character))
                (<= (char-code character) #xdfff))
           (error "JSON strings must contain Unicode scalar values."))
          (t (%json-append-character buffer character)))))))

(defun %json-literal (parser literal value)
  (let* ((start (%json-parser-position parser))
         (end (+ start (length literal)))
         (text (%json-parser-text parser)))
    (unless (and (<= end (length text))
                 (string= text literal :start1 start :end1 end))
      (error "Invalid JSON literal."))
    (setf (%json-parser-position parser) end)
    value))

(defun %json-number-digit-p (character)
  (and character (digit-char-p character 10)))

(defun %json-number-too-long-p (parser start)
  (> (- (%json-parser-position parser) start) +json-max-number-lexeme+))

(defun %json-read-exponent (text start end)
  (let ((negative nil) (position start) (value 0) (saturated nil))
    (when (and (< position end)
               (or (char= (char text position) #\+)
                   (char= (char text position) #\-)))
      (setf negative (char= (char text position) #\-))
      (incf position))
    (when (= position end) (error "JSON exponent needs digits."))
    (loop while (< position end) do
      (let ((digit (digit-char-p (char text position) 10)))
        (unless digit (error "Invalid JSON exponent."))
        (if (> value 1000000)
            (setf saturated t)
            (setf value (+ (* value 10) digit)))
        (incf position)))
    (if saturated
        (if negative -1000001 1000001)
        (if negative (- value) value))))

(defun %json-decimal-float (text start end negative digits fraction-digits exponent
                            significant-digits)
  (declare (ignore text start end))
  (let ((zero (if negative (- 0.0d0) 0.0d0)))
    (when (zerop digits) (return-from %json-decimal-float zero))
    (let ((order (+ exponent (- fraction-digits) (1- significant-digits))))
      (when (> order 309)
        (error "JSON number is outside the finite double-float range."))
      (when (< order -400)
        (return-from %json-decimal-float zero))
      (let ((scale (- exponent fraction-digits)))
        (when (> scale 1000)
          (error "JSON number exponent is too large."))
        (when (< scale -1000)
          (return-from %json-decimal-float zero))
          (let* ((power (handler-case (expt 10 (abs scale))
                        (error () nil))))
          (unless power
            (error "JSON number exponent is outside the finite range."))
          (let* ((exact (if (minusp scale)
                            (/ digits power)
                            (* digits power)))
                 (result (handler-case (coerce exact 'double-float)
                           (error () nil))))
            (unless result
              (error "JSON number cannot be represented as a double-float."))
            (when negative (setf result (- result)))
            (unless (%json-finite-float-p result)
              (error "JSON number is outside the finite double-float range."))
            result))))))

(defun %json-number-value (text start end)
  (let* ((position start)
         (negative (and (< position end) (char= (char text position) #\-)))
         (digits-start (if negative (1+ position) position))
         (dot (position #\. text :start digits-start :end end))
         (exponent-marker
           (or (position #\e text :start digits-start :end end :test #'char-equal)
               (position #\E text :start digits-start :end end)))
         (mantissa-end (or exponent-marker end))
         (dot (and dot (< dot mantissa-end) dot))
         (fraction-start (and dot (1+ dot)))
         (fraction-digits (if dot (- mantissa-end fraction-start) 0))
         (exponent (if exponent-marker
                       (%json-read-exponent text (1+ exponent-marker) end)
                       0))
         (digits 0)
         (significant 0)
         (seen-significant nil))
    (loop for index from digits-start below mantissa-end do
      (unless (char= (char text index) #\.)
        (let ((digit (digit-char-p (char text index) 10)))
          (unless digit (error "Invalid JSON number."))
          (setf digits (+ (* digits 10) digit))
          (when (or seen-significant (plusp digit))
            (setf seen-significant t)
            (incf significant)))))
    (when (zerop significant) (setf significant 1))
    (if (and (null dot) (null exponent-marker)
             (%json-number-in-range-p (if negative (- digits) digits)))
        (if negative (- digits) digits)
        (%json-decimal-float text start end negative digits fraction-digits exponent significant))))

(defun %json-parse-number (parser)
  (let* ((text (%json-parser-text parser))
         (start (%json-parser-position parser)))
    (when (eql (%json-parser-peek parser) #\-)
      (incf (%json-parser-position parser)))
    (let ((character (%json-parser-peek parser)))
      (cond
        ((eql character #\0)
         (incf (%json-parser-position parser))
         (when (%json-number-digit-p (%json-parser-peek parser))
           (error "JSON numbers cannot have leading zeroes.")))
        ((and character (digit-char-p character 10) (not (char= character #\0)))
         (loop while (%json-number-digit-p (%json-parser-peek parser)) do
           (incf (%json-parser-position parser))
           (when (%json-number-too-long-p parser start)
             (error "JSON number lexeme exceeds ~D characters." +json-max-number-lexeme+))))
        (t (error "Invalid JSON number."))))
    (when (char= (or (%json-parser-peek parser) #\Null) #\.)
      (incf (%json-parser-position parser))
      (unless (%json-number-digit-p (%json-parser-peek parser))
        (error "JSON fraction needs digits."))
      (loop while (%json-number-digit-p (%json-parser-peek parser)) do
        (incf (%json-parser-position parser))
        (when (%json-number-too-long-p parser start)
          (error "JSON number lexeme exceeds ~D characters." +json-max-number-lexeme+))))
    (when (find (or (%json-parser-peek parser) #\Null) "eE" :test #'char=)
      (incf (%json-parser-position parser))
      (when (find (or (%json-parser-peek parser) #\Null) "+-" :test #'char=)
        (incf (%json-parser-position parser)))
      (unless (%json-number-digit-p (%json-parser-peek parser))
        (error "JSON exponent needs digits."))
      (loop while (%json-number-digit-p (%json-parser-peek parser)) do
        (incf (%json-parser-position parser))
        (when (%json-number-too-long-p parser start)
          (error "JSON number lexeme exceeds ~D characters." +json-max-number-lexeme+))))
    (%json-number-value text start (%json-parser-position parser))))

(declaim (ftype function %json-parse-value))

(defun %json-parse-array (parser depth)
  (%json-expect parser #\[)
  (%json-skip-whitespace parser)
  (if (eql (%json-parser-peek parser) #\])
      (progn (incf (%json-parser-position parser)) (list :json-array nil))
      (let ((values nil))
        (loop
          (push (%json-parse-value parser (1+ depth)) values)
          (%json-skip-whitespace parser)
          (case (%json-parser-peek parser)
            (#\,
             (incf (%json-parser-position parser))
             (%json-skip-whitespace parser)
             (when (eql (%json-parser-peek parser) #\])
               (error "Trailing comma in JSON array.")))
            (#\]
             (incf (%json-parser-position parser))
             (return (list :json-array (nreverse values))))
            (t (error "Expected comma or closing bracket in JSON array.")))))))

(defun %json-parse-object (parser depth)
  (%json-expect parser #\{)
  (%json-skip-whitespace parser)
  (if (eql (%json-parser-peek parser) #\})
      (progn (incf (%json-parser-position parser)) (list :json-object nil))
      (let ((members nil)
            (seen (make-hash-table :test #'equal)))
        (loop
          (unless (eql (%json-parser-peek parser) #\")
            (error "JSON object keys must be strings."))
          (let ((key (%json-parse-string parser)))
            (%json-skip-whitespace parser)
            (%json-expect parser #\:)
            (%json-skip-whitespace parser)
            (multiple-value-bind (entry presentp) (gethash key seen)
              (when (and presentp (%json-parser-reject-duplicate-keys parser))
                (error "Duplicate JSON object key ~S." key))
              (let ((value (%json-parse-value parser (1+ depth))))
                (if presentp
                    (setf (cdr entry) value)
                    (let ((entry (cons key value)))
                      (setf (gethash key seen) entry)
                      (push entry members))))))
          (%json-skip-whitespace parser)
          (case (%json-parser-peek parser)
            (#\,
             (incf (%json-parser-position parser))
             (%json-skip-whitespace parser)
             (when (eql (%json-parser-peek parser) #\})
               (error "Trailing comma in JSON object.")))
            (#\}
             (incf (%json-parser-position parser))
             (return (list :json-object (nreverse members))))
            (t (error "Expected comma or closing brace in JSON object.")))))))

(defun %json-parse-value (parser depth)
  (%json-node parser depth)
  (let ((character (%json-parser-peek parser)))
    (cond
      ((eql character #\{) (%json-parse-object parser depth))
      ((eql character #\[) (%json-parse-array parser depth))
      ((eql character #\") (%json-parse-string parser))
      ((eql character #\t) (%json-literal parser "true" t))
      ((eql character #\f) (%json-literal parser "false" +json-false+))
      ((eql character #\n) (%json-literal parser "null" nil))
      ((or (eql character #\-) (and character (digit-char-p character 10)))
       (%json-parse-number parser))
      (t (error "Unexpected character in JSON input: ~S" character)))))

(defun parse-json (text &key reject-duplicate-keys)
  "Parse one bounded JSON value without invoking the Lisp reader."
  (check-type text string)
  (%json-text-size text)
  (let ((parser (%make-json-parser text reject-duplicate-keys)))
    (%json-skip-whitespace parser)
    (when (%json-parser-eof-p parser)
      (error "JSON input is empty."))
    (let ((value (%json-parse-value parser 1)))
      (%json-skip-whitespace parser)
      (unless (%json-parser-eof-p parser)
        (error "Trailing data after JSON value."))
      (%json-validate-value value)
      value)))

(defun %json-write-string (stream value)
  (write-char #\" stream)
  (loop for character across value do
    (case character
      (#\" (write-string "\\\"" stream))
      (#\\ (write-string "\\\\" stream))
      (#\Backspace (write-string "\\b" stream))
      (#\Page (write-string "\\f" stream))
      (#\Newline (write-string "\\n" stream))
      (#\Return (write-string "\\r" stream))
      (#\Tab (write-string "\\t" stream))
      (t (if (< (char-code character) #x20)
             (format stream "\\u~4,'0X" (char-code character))
             (write-char character stream)))))
  (write-char #\" stream))

(defun %json-format-number (value)
  (cond
    ((integerp value)
     (unless (%json-number-in-range-p value)
       (error "JSON integer is outside the data range."))
     (princ-to-string value))
    ((%json-ratio-p value)
     (unless (and (<= (- (expt 2 63)) (numerator value) (1- (expt 2 64)))
                  (<= 1 (denominator value) (1- (expt 2 64))))
       (error "JSON rational is outside the data range."))
     (%json-format-number (coerce value 'double-float)))
    ((floatp value)
     (unless (%json-finite-float-p value)
       (error "JSON numbers must be finite."))
     (let ((text (format nil "~,17E" (coerce value 'double-float))))
       (substitute #\e #\d (substitute #\e #\D text))))
    (t (error "Value of type ~A is not a JSON number." (type-of value)))))

(defun %json-indent (stream depth)
  (dotimes (ignored (* 2 depth))
    (declare (ignorable ignored))
    (write-char #\Space stream)))

(defun %json-write-array (stream values depth pretty)
  (write-char #\[ stream)
  (unless (null values)
    (when pretty (terpri stream))
    (loop for tail on values do
      (when pretty (%json-indent stream (1+ depth)))
      (%json-write-value stream (car tail) (1+ depth) pretty)
      (when (cdr tail)
        (write-char #\, stream)
        (when pretty (terpri stream))))
    (when pretty
      (terpri stream)
      (%json-indent stream depth)))
  (write-char #\] stream))

(defun %json-write-object (stream members depth pretty)
  (write-char #\{ stream)
  (unless (null members)
    (when pretty (terpri stream))
    (loop for tail on members do
      (when pretty (%json-indent stream (1+ depth)))
      (%json-write-string stream (caar tail))
      (if pretty (write-string ": " stream) (write-char #\: stream))
      (%json-write-value stream (cdar tail) (1+ depth) pretty)
      (when (cdr tail)
        (write-char #\, stream)
        (when pretty (terpri stream))))
    (when pretty
      (terpri stream)
      (%json-indent stream depth)))
  (write-char #\} stream))

(defun %json-write-value (stream value depth pretty)
  (cond
    ((null value) (write-string "null" stream))
    ((eq value t) (write-string "true" stream))
    ((eq value +json-false+) (write-string "false" stream))
    ((stringp value) (%json-write-string stream value))
    ((or (integerp value) (%json-ratio-p value) (floatp value))
     (write-string (%json-format-number value) stream))
    ((and (consp value) (eq (car value) :json-array))
     (%json-write-array stream (second value) depth pretty))
    ((and (consp value) (eq (car value) :json-object))
     (%json-write-object stream (second value) depth pretty))
    (t (error "Value of type ~A is not JSON data." (type-of value)))))

(defun write-json (value &key pretty)
  "Serialize bounded JSON data; PRETTY uses two-space indentation."
  (%json-validate-value value)
  (%json-output-size value 0 pretty)
  (with-output-to-string (stream)
    (%json-write-value stream value 0 pretty)))
