(in-package #:tomoe)

(defparameter *lua-pattern-length-limit* 65536)
(defparameter *lua-pattern-text-limit* 65536)
(defparameter *lua-pattern-work-limit* 1000000)
(defparameter *lua-pattern-depth-limit* 200)
(defparameter *lua-pattern-capture-limit* 32)

(defun %lua-pattern-class-p (byte class)
  (let* ((lower (if (<= 65 class 90) (+ class 32) class))
         (alpha (or (<= 65 byte 90) (<= 97 byte 122)))
         (digit (<= 48 byte 57))
         (result
           (case lower
             (97 alpha)
             (99 (or (< byte 32) (= byte 127)))
             (100 digit)
             (103 (<= 33 byte 126))
             (108 (<= 97 byte 122))
             (112 (and (<= 33 byte 126)
                       (not alpha) (not digit)))
             (115 (or (= byte 32) (<= 9 byte 13)))
             (117 (<= 65 byte 90))
             (119 (or alpha digit))
             (120 (or digit (<= 65 byte 70)
                       (<= 97 byte 102)))
             (122 (zerop byte))
             (otherwise
              (return-from %lua-pattern-class-p (= byte class))))))
    (if (<= 65 class 90) (not result) result)))

(defun lua-pattern-match-p (pattern text)
  "Whether TEXT contains a case-sensitive Lua 5.4 PATTERN match.
Strings are encoded as UTF-8 and matched as bytes. Character classes use the
default C locale. As in Lua's string.match, malformed syntax signals an error
when matching reaches it; an unfinished capture errors on an otherwise
successful match. Length, work, capture and recursion limits also signal errors."
  (check-type pattern string)
  (check-type text string)
  (when (> (length pattern) *lua-pattern-length-limit*)
    (error "Lua pattern exceeds its byte length limit."))
  (when (> (length text) *lua-pattern-text-limit*)
    (error "Lua pattern text exceeds its byte length limit."))
  (let* ((pattern (sb-ext:string-to-octets pattern :external-format :utf-8))
         (text (sb-ext:string-to-octets text :external-format :utf-8))
         (pattern-length (length pattern))
         (text-length (length text))
         (work 0)
         (capture-count 0)
         (capture-starts (make-array *lua-pattern-capture-limit*
                                    :initial-element 0))
         (capture-lengths (make-array *lua-pattern-capture-limit*
                                     :initial-element -1)))
    (when (> pattern-length *lua-pattern-length-limit*)
      (error "Lua pattern exceeds its byte length limit."))
    (when (> text-length *lua-pattern-text-limit*)
      (error "Lua pattern text exceeds its byte length limit."))
    (labels
        ((tick ()
           (when (> (incf work) *lua-pattern-work-limit*)
             (error "Lua pattern exceeds its work limit.")))
         (pattern-byte (index)
           (if (< index pattern-length) (aref pattern index) 0))
         (text-byte (index)
           (if (< index text-length) (aref text index) 0))
         (class-end (index)
           (case (pattern-byte index)
             (37
              (when (= (1+ index) pattern-length)
                (error "Malformed Lua pattern (ends with '%')."))
              (+ index 2))
             (91
              (let ((cursor (1+ index)))
                (when (= (pattern-byte cursor) 94) (incf cursor))
                (loop
                  (tick)
                  (when (>= cursor pattern-length)
                    (error "Malformed Lua pattern (missing ']')."))
                  (let ((byte (pattern-byte cursor)))
                    (incf cursor)
                    (when (and (= byte 37) (< cursor pattern-length))
                      (incf cursor)))
                  (when (= (pattern-byte cursor) 93)
                    (return (1+ cursor))))))
             (otherwise (1+ index))))
         (set-match-p (byte start end)
           (let* ((negated (= (pattern-byte (1+ start)) 94))
                  (cursor (+ start (if negated 2 1))))
             (loop while (< cursor end) do
               (tick)
               (let ((item (pattern-byte cursor)))
                 (cond
                   ((= item 37)
                    (incf cursor)
                    (when (%lua-pattern-class-p byte (pattern-byte cursor))
                      (return-from set-match-p (not negated))))
                   ((and (= (pattern-byte (1+ cursor)) 45)
                         (< (+ cursor 2) end))
                    (incf cursor 2)
                    (when (<= item byte (pattern-byte cursor))
                      (return-from set-match-p (not negated))))
                   ((= item byte)
                    (return-from set-match-p (not negated)))))
               (incf cursor))
             negated))
         (single-match-p (source start end)
           (tick)
           (and (< source text-length)
                (let ((byte (text-byte source)))
                  (case (pattern-byte start)
                    (46 t)
                    (37 (%lua-pattern-class-p byte (pattern-byte (1+ start))))
                    (91 (set-match-p byte start (1- end)))
                    (otherwise (= byte (pattern-byte start)))))))
         (balanced-match (source start)
           (when (>= (1+ start) pattern-length)
             (error "Malformed Lua pattern (missing arguments to '%b')."))
           (let ((opening (pattern-byte start))
                 (closing (pattern-byte (1+ start)))
                 (balance 1))
             (when (= (text-byte source) opening)
               (loop for cursor from (1+ source) below text-length do
                 (tick)
                 (let ((byte (text-byte cursor)))
                   (cond ((= byte closing)
                          (when (zerop (decf balance))
                            (return-from balanced-match (1+ cursor))))
                         ((= byte opening) (incf balance))))))))
         (capture-match (source number)
           (let ((index (- number 49)))
             (unless (and (<= 0 index) (< index capture-count)
                          (/= (aref capture-lengths index) -1))
               (error "Invalid Lua capture index %~D." (- number 48)))
             (let ((length (aref capture-lengths index))
                   (start (aref capture-starts index)))
               (when (and (>= length 0) (<= length (- text-length source)))
                 (loop for offset below length do
                   (tick)
                   (unless (= (text-byte (+ source offset))
                              (text-byte (+ start offset)))
                     (return-from capture-match nil)))
                 (+ source length)))))
         (start-capture (source start position-p depth)
           (when (>= capture-count *lua-pattern-capture-limit*)
             (error "Too many Lua pattern captures."))
           (let ((index capture-count))
             (setf (aref capture-starts index) source
                   (aref capture-lengths index) (if position-p -2 -1))
             (incf capture-count)
             (let ((result (match-pattern source start (1+ depth))))
               (unless result (decf capture-count))
               result)))
         (end-capture (source start depth)
           (let ((index (loop for i downfrom (1- capture-count) to 0
                              when (= (aref capture-lengths i) -1) return i)))
             (unless index (error "Invalid Lua pattern capture."))
             (setf (aref capture-lengths index)
                   (- source (aref capture-starts index)))
             (let ((result (match-pattern source start (1+ depth))))
               (unless result (setf (aref capture-lengths index) -1))
               result)))
         (max-expand (source start end depth)
           (let ((cursor source))
             (loop while (single-match-p cursor start end) do (incf cursor))
             (loop for candidate downfrom cursor to source
                   for result = (match-pattern candidate (1+ end) (1+ depth))
                   when result return result)))
         (min-expand (source start end depth)
           (loop
             (let ((result (match-pattern source (1+ end) (1+ depth))))
               (when result (return result)))
             (unless (single-match-p source start end) (return nil))
             (incf source)))
         (match-pattern (source start depth)
           (when (>= depth *lua-pattern-depth-limit*)
             (error "Lua pattern exceeds its recursion depth limit."))
           (loop
             (tick)
             (when (= start pattern-length) (return source))
             (let* ((byte (pattern-byte start))
                    (escaped (and (= byte 37) (pattern-byte (1+ start)))))
               (cond
                 ((= byte 40)
                  (let ((position-p (= (pattern-byte (1+ start)) 41)))
                    (return (start-capture source (+ start (if position-p 2 1))
                                           position-p depth))))
                 ((= byte 41)
                  (return (end-capture source (1+ start) depth)))
                 ((and (= byte 36) (= (1+ start) pattern-length))
                  (return (and (= source text-length) source)))
                 ((eql escaped 98)
                  (setf source (balanced-match source (+ start 2)))
                  (unless source (return nil))
                  (incf start 4))
                 ((eql escaped 102)
                  (incf start 2)
                  (unless (= (pattern-byte start) 91)
                    (error "Missing '[' after '%f' in Lua pattern."))
                  (let ((end (class-end start))
                        (previous (if (zerop source) 0 (text-byte (1- source)))))
                    (unless (and (not (set-match-p previous start (1- end)))
                                 (set-match-p (text-byte source) start (1- end)))
                      (return nil))
                    (setf start end)))
                 ((and escaped (<= 48 escaped 57))
                  (setf source (capture-match source escaped))
                  (unless source (return nil))
                  (incf start 2))
                 (t
                  (let* ((end (class-end start))
                         (suffix (pattern-byte end)))
                    (cond
                      ((not (single-match-p source start end))
                       (unless (member suffix '(42 63 45)) (return nil))
                       (setf start (1+ end)))
                      ((= suffix 63)
                       (let ((result (match-pattern (1+ source) (1+ end) (1+ depth))))
                         (when result (return result)))
                       (setf start (1+ end)))
                      ((or (= suffix 43) (= suffix 42))
                       (return (max-expand (+ source (if (= suffix 43) 1 0))
                                           start end depth)))
                      ((= suffix 45)
                       (return (min-expand source start end depth)))
                      (t (incf source) (setf start end))))))))))
      (let* ((anchored (= (pattern-byte 0) 94))
             (start (if anchored 1 0)))
        (loop for source from 0 to (if anchored 0 text-length) do
          (setf capture-count 0)
          (when (match-pattern source start 0)
            (loop for index below capture-count do
              (when (= (aref capture-lengths index) -1)
                (error "Unfinished Lua pattern capture.")))
            (return-from lua-pattern-match-p t)))
        nil))))
