(in-package #:tomoe)

(sb-alien:define-alien-routine ("tomoe_process_abi" %process-abi) sb-alien:int)
(sb-alien:define-alien-routine ("tomoe_process_group_alive" %process-group-alive) sb-alien:int (job (* t)))
(sb-alien:define-alien-routine ("tomoe_process_start" %process-start) (* t)
  (argv (* (* sb-alien:unsigned-char))) (cwd (sb-alien:c-string :external-format :utf-8))
  (environment (* (* sb-alien:unsigned-char))) (error (* sb-alien:int)))

(defstruct managed-process owner identity arguments lease history session-link
  (status :pending) (deadline 0) (attempts 0) code error (turn 0))
(defstruct process-plan active retired history)

(defun process-kind (job) (first (managed-process-arguments job)))
(defun session-process-p (job) (member (process-kind job) '(:once :session)))
(defun managed-process-reservations (runtime active retired)
  (+ (length (runtime-once-processes runtime)) (length retired)
     (count :pending (runtime-pending-spawns runtime) :key #'managed-process-status)
     (count-if (lambda (job) (or (eq :service (process-kind job))
                                (eq :pending (managed-process-status job)))) active)))
(defun process-due-p (owner args history)
  (or (null (car history))
      (and (eq :once-per-config-version (sixth args))
           (not (eq (car history) (spec-token owner))))))

(defun prepare-managed-processes (runtime mounts)
  "Resolve declarations and reserve bounded ownership before native publication."
  (let ((previous (make-hash-table :test #'equal))
        (history (make-hash-table :test #'equal)) (active nil) (count 0))
    (dolist (job (runtime-managed-processes runtime))
      (setf (gethash (managed-process-identity job) previous) job))
    (when (runtime-process-history runtime)
      (maphash (lambda (key stamp) (when (car stamp) (setf (gethash key history) stamp)))
               (runtime-process-history runtime)))
    (dolist (mount mounts)
      (let ((owner (mounted-spec mount)))
        (dolist (effect (mounted-effects mount))
          (when (eq :process (effect-kind effect))
            (when (> (incf count) 64) (error "More than 64 process declarations."))
            (let* ((args (effect-arguments effect))
                   (key (list (spec-source owner) (spec-name owner) (second args)))
                   (old (gethash key previous))
                   (same (and old (equal args (managed-process-arguments old))))
                   (same-source (and old (eq owner (managed-process-owner old))))
                   (once (eq :once (first args)))
                   (stamp (when once
                            (or (gethash key history)
                                (setf (gethash key history)
                                      (or (and old (eq :once (process-kind old)) (managed-process-history old))
                                          (list nil))))))
                   (due (and once (process-due-p owner args stamp)))
                   (keep (and same
                              (if once
                                  (or (not due)
                                      (and same-source (not (eq :spawn-error (managed-process-status old)))))
                                  (or same-source
                                      (and (eq :keep-if-unchanged (eighth args))
                                           (member (managed-process-status old) '(:running :waiting)))))))
                   (job (if keep (if same-source old (copy-managed-process old))
                            (make-managed-process :identity key :arguments args :history stamp
                                                  :lease (make-process-lease)
                                                  :status (if (and once (not due)) :recorded :pending)))))
              (unless (eq job old)
                (setf (managed-process-owner job) owner)
                (when (and once (not keep))
                  (setf (managed-process-session-link job) (list (managed-process-lease job)))))
              (push job active))))))
    (when (> (hash-table-count history) 4096) (error "More than 4096 one-shot process identities."))
    (let* ((leases (mapcar #'managed-process-lease active))
           (retired (append (runtime-retired-processes runtime)
                            (remove-if (lambda (job)
                                         (or (eq :once (process-kind job))
                                             (member (managed-process-lease job) leases :test #'eq)
                                             (null (process-lease-process (managed-process-lease job)))))
                                       (runtime-managed-processes runtime)))))
      (when (> (managed-process-reservations runtime active retired) 128)
        (error "More than 128 live or reserved managed processes."))
      (when (plusp count)
        (open-execution-support)
        (unless (= 1 (%process-abi)) (error "Incompatible process helper ABI.")))
      (make-process-plan :active (nreverse active) :retired retired :history history))))

(defun prepare-session-spawns (runtime commands plan)
  "Reserve every accepted imperative launch before publication, including those
following a reload command. Launch buffers and tokens are acquired at execution."
  (let ((count (count-if (lambda (command) (member (command-kind command) '(:launch :spawn))) commands)))
    (when (> (+ count (managed-process-reservations runtime (process-plan-active plan)
                                                    (process-plan-retired plan))) 128)
      (error "More than 128 live or reserved managed processes."))
    (when (plusp count)
      (open-execution-support)
      (unless (= 1 (%process-abi)) (error "Incompatible process helper ABI.")))
    (loop for command in commands collect
      (when (member (command-kind command) '(:launch :spawn))
        (destructuring-bind (launch cwd env)
            (if (eq :launch (command-kind command))
                (list (command-arguments command) nil nil) (command-arguments command))
          (let ((lease (make-process-lease)))
            (make-managed-process :arguments (list :session nil launch cwd env nil nil nil)
                                  :lease lease :session-link (list lease))))))))

(defun install-managed-processes (runtime plan)
  (setf (runtime-managed-processes runtime) (process-plan-active plan)
        (runtime-retired-processes runtime) (process-plan-retired plan)
        (runtime-process-history runtime) (process-plan-history plan))
  (dolist (job (runtime-retired-processes runtime))
    (unless (eq :cancelled (managed-process-status job))
      (setf (managed-process-status job) :cancelled)
      (kill-execution runtime (managed-process-lease job))
      (setf (managed-process-owner job) nil (managed-process-arguments job) nil))))

(defun call-with-process-strings (strings callback)
  "Keep a bounded UTF-8 vector and its pointer table alive for one native call."
  (when (> (length strings) 4096) (error "More than 4096 process strings."))
  (let* ((chunks (mapcar (lambda (string) (sb-ext:string-to-octets string :external-format :utf-8
                                                                      :null-terminate t)) strings))
         (size (reduce #'+ chunks :key #'length :initial-value 0)))
    (when (> size 1048576) (error "Encoded process strings exceed 1 MiB."))
    (let ((bytes (make-array (max 1 size) :element-type '(unsigned-byte 8)))
          (pointers (sb-alien:make-alien (* sb-alien:unsigned-char) (1+ (length strings)))))
      (unwind-protect
           (sb-sys:with-pinned-objects (bytes)
             (loop with offset = 0 for chunk in chunks for index from 0 do
                     (replace bytes chunk :start1 offset)
                     (setf (sb-alien:deref pointers index)
                           (sb-alien:sap-alien (sb-sys:sap+ (sb-sys:vector-sap bytes) offset)
                                               (* sb-alien:unsigned-char)))
                     (incf offset (length chunk)))
             (setf (sb-alien:deref pointers (length strings))
                   (sb-alien:sap-alien (sb-sys:int-sap 0) (* sb-alien:unsigned-char)))
             (funcall callback pointers))
        (sb-alien:free-alien pointers)))))

(defun process-environment (overrides)
  (append (loop for (name . value) in overrides collect (concatenate 'string name "=" value))
          (remove-if (lambda (entry)
                       (let ((end (position #\= entry)))
                         (and end (assoc (subseq entry 0 end) overrides :test #'equal))))
                     (sb-ext:posix-environ))))

(defun start-managed-process (runtime job)
  (let* ((args (managed-process-arguments job)) (command (third args))
         (argv (if (stringp command)
                   (list (or (sb-ext:posix-getenv "TOMOE_SHELL") "/bin/sh") "-c" command)
                   command))
         (cwd (fourth args)) (lease (managed-process-lease job)) (token nil))
    (when (and cwd (not (char= (char cwd 0) #\/)))
      (setf cwd (concatenate 'string (directory-namestring (spec-source (managed-process-owner job))) cwd)))
    (incf (managed-process-attempts job))
    (handler-case
        (progn
          (when (eq :session (process-kind job))
            (setf token (%activation-token (runtime-backend runtime)))
            (unless token (error "Cannot issue application activation token.")))
          (call-with-process-strings
         argv (lambda (argv-pointer)
                (call-with-process-strings
                 (process-environment
                  (append (fifth args)
                          (when token
                            (loop for name in '("XDG_ACTIVATION_TOKEN" "DESKTOP_STARTUP_ID")
                                  unless (assoc name (fifth args) :test #'equal)
                                    collect (cons name token)))))
                 (lambda (env-pointer)
                   (sb-alien:with-alien ((error-code sb-alien:int))
                     (let ((child (%process-start argv-pointer cwd env-pointer (sb-alien:addr error-code))))
                       (when (sb-alien:null-alien child)
                         (error "Cannot start process ~S: errno ~D."
                                (subseq (first argv) 0 (min 512 (length (first argv)))) error-code))
                       (setf (process-lease-process lease) child)
                       (when (session-process-p job)
                         (setf (cdr (managed-process-session-link job)) (runtime-once-processes runtime)
                               (runtime-once-processes runtime) (managed-process-session-link job)
                               (managed-process-session-link job) nil)
                         (when (managed-process-history job)
                           (setf (car (managed-process-history job)) (spec-token (managed-process-owner job)))))
                       (setf (process-lease-stopped lease) nil
                             (process-lease-stop-error lease) nil
                             (managed-process-status job) :running
                             (managed-process-error job) nil (managed-process-code job) nil
                             (managed-process-deadline job) (+ (get-internal-real-time) internal-time-units-per-second))
                       (when (session-process-p job)
                         (setf (managed-process-status job) :launched)))))))))
      (serious-condition (condition)
        (when token (%activation-revoke (runtime-backend runtime) token))
        (setf (managed-process-status job) :spawn-error
              (managed-process-error job) (execution-error-text condition))
        (when (process-lease-process lease)
          (kill-execution runtime lease)
          (when (eq :service (process-kind job))
            (setf (managed-process-status job) :stopping (managed-process-deadline job) 0)))
        (record-error runtime condition)))))

(defun reap-process-lease (runtime lease &optional cancel)
  (when cancel (kill-execution runtime lease))
  (let ((result (%exec-poll (process-lease-process lease))))
    (when (minusp result) (error "Cannot reap managed process: errno ~D." (- result)))
    (when (and (plusp result) (kill-execution runtime lease))
      (let ((code (%exec-code (process-lease-process lease))))
        (release-execution lease)
        (values result code)))))

(defun reap-managed-processes (runtime)
  (setf (runtime-retired-processes runtime)
        (delete-if (lambda (job) (reap-process-lease runtime (managed-process-lease job) t))
                   (runtime-retired-processes runtime))
        (runtime-once-processes runtime)
        (delete-if (lambda (lease)
                     (if (process-lease-stopped lease)
                         (reap-process-lease runtime lease t)
                         (let ((result (%exec-poll (process-lease-process lease))))
                           (when (minusp result) (error "Cannot reap session process: errno ~D." (- result)))
                           (when (plusp result)
                             (let ((group (%process-group-alive (process-lease-process lease))))
                               (when (minusp group) (error "Cannot inspect session process group: errno ~D." (- group)))
                               (when (zerop group) (release-execution lease) t))))))
                   (runtime-once-processes runtime))))

(defun service-managed-processes (runtime)
  (reconcile-backend-observations runtime)
  (reap-managed-processes runtime)
  (let ((stop-at (+ (get-internal-real-time) (ceiling (* 8 internal-time-units-per-second) 1000)))
        (serviced 0)
        (jobs (stable-sort (copy-list (runtime-managed-processes runtime)) #'< :key #'managed-process-turn)))
    (dolist (job jobs)
      (reconcile-backend-observations runtime)
      (unless (and (runtime-running runtime) (not *stop-requested*)) (return))
      (when (and (member job (runtime-managed-processes runtime) :test #'eq)
                 (member (managed-process-status job) '(:pending :running :waiting :stopping))
                 (>= (get-internal-real-time) (managed-process-deadline job))
                 (or (process-lease-process (managed-process-lease job))
                     (not (find (managed-process-identity job) (runtime-retired-processes runtime)
                                :test #'equal :key #'managed-process-identity))))
        (unless (and (< serviced 64) (or (zerop serviced) (< (get-internal-real-time) stop-at))) (return))
        (incf serviced)
        (setf (managed-process-turn job) (incf (runtime-process-turn runtime)))
        (let ((lease (managed-process-lease job)))
          (when (and (member (managed-process-status job) '(:running :stopping)) (process-lease-process lease))
            (multiple-value-bind (status code) (reap-process-lease runtime lease (eq :stopping (managed-process-status job)))
              (if status
                  (setf (managed-process-code job) code
                        (managed-process-status job)
                        (cond ((eq :stopping (managed-process-status job)) :spawn-error)
                              ((or (eq :on-exit (seventh (managed-process-arguments job)))
                                   (and (eq :on-failure (seventh (managed-process-arguments job)))
                                        (or (= 2 status) (not (zerop code))))) :waiting)
                              (t :stopped)))
                  (setf (managed-process-deadline job) (+ (get-internal-real-time) internal-time-units-per-second)))))
          (when (and (member (managed-process-status job) '(:pending :waiting))
                     (not (find (managed-process-identity job) (runtime-retired-processes runtime)
                                :test #'equal :key #'managed-process-identity)))
            (start-managed-process runtime job)))))))

(defun stop-managed-processes (runtime)
  (setf (runtime-pending-spawns runtime) nil)
  (install-managed-processes
   runtime (make-process-plan :active nil :history (make-hash-table :test #'equal)
                              :retired (append (runtime-retired-processes runtime)
                                               (remove-if (lambda (job)
                                                            (or (eq :once (process-kind job))
                                                                (null (process-lease-process (managed-process-lease job)))))
                                                          (runtime-managed-processes runtime)))))
  (dolist (lease (runtime-once-processes runtime)) (kill-execution runtime lease))
  (loop repeat 100 while (or (runtime-retired-processes runtime) (runtime-once-processes runtime)) do
    (dolist (lease (runtime-once-processes runtime)) (kill-execution runtime lease))
    (reap-managed-processes runtime)
    (when (or (runtime-retired-processes runtime) (runtime-once-processes runtime)) (sleep 0.01)))
  (when (or (runtime-retired-processes runtime) (runtime-once-processes runtime))
    (error "Killed managed processes have not yet become reapable.")))

(defun describe-managed-processes (runtime)
  (loop for job in (runtime-managed-processes runtime)
        for args = (managed-process-arguments job)
        collect (list :owner (spec-name (managed-process-owner job)) :name (second args) :kind (first args)
                      :status (managed-process-status job) :attempts (managed-process-attempts job)
                      :running (not (null (process-lease-process (managed-process-lease job))))
                      :code (managed-process-code job) :error (managed-process-error job))))
