(in-package #:tomoe)

(defun %ui-list (value limit description)
  (let ((tail value) (count 0))
    (loop while (consp tail) do
      (when (> (incf count) limit) (error "~A exceeds its list budget." description))
      (setf tail (cdr tail)))
    (unless (null tail) (error "~A must be a proper list." description)))
  value)

(defun %ui-properties (properties allowed)
  (%ui-list properties 64 "UI properties")
  (unless (evenp (length properties)) (error "UI properties need key/value pairs."))
  (let ((seen nil))
    (loop for key in properties by #'cddr do
      (unless (member key allowed) (error "Unsupported UI property ~S." key))
      (when (member key seen) (error "Duplicate UI property ~S." key))
      (push key seen)))
  properties)

(defun %ui-length (value &optional nullable signed)
  (if (and nullable (null value)) nil
      (let ((number (%double-float value)))
        (unless (<= (if signed -16384d0 0d0) number 16384d0)
          (error "UI length is outside its supported range: ~S." value))
        number)))

(defun %ui-string (value limit &optional (empty t))
  (unless (and (stringp value) (<= (length value) limit)
               (or empty (plusp (length value)))
               (not (find #\Null value)))
    (error "Expected a bounded UI string without NUL characters."))
  (copy-seq value))

(defun %ui-key (value &optional nullable)
  (if (and nullable (null value)) nil
      (progn
        (unless (keywordp value) (error "UI names and commands must be keywords."))
        (%ui-string (symbol-name value) 128 nil)
        value)))

(defun %ui-color (value &optional nullable)
  (cond ((and nullable (null value)) nil)
        ((typep value '(unsigned-byte 32)) value)
        ((and (stringp value) (member (length value) '(4 7 9))
              (char= (char value 0) #\#)
              (every (lambda (c) (digit-char-p c 16)) (subseq value 1)))
         (let ((number (parse-integer value :start 1 :radix 16)))
           (case (length value)
             (4 (logior (ash (* 17 (ldb (byte 4 8) number)) 24)
                        (ash (* 17 (ldb (byte 4 4) number)) 16)
                        (ash (* 17 (ldb (byte 4 0) number)) 8) 255))
             (7 (logior (ash number 8) 255))
             (9 number))))
        (t (error "UI color must be RRGGBBAA or #rgb/#rrggbb/#rrggbbaa."))))

(defun %ui-edges (value &optional signed)
  (if (%finite-real-p value)
      (make-list 4 :initial-element (%ui-length value nil signed))
      (progn
        (%ui-list value 4 "UI edges")
        (unless (= (length value) 4) (error "UI edges need top/right/bottom/left."))
        (mapcar (lambda (edge) (%ui-length edge nil signed)) value))))

(defun %ui-choice (value choices)
  (unless (member value choices) (error "Unsupported UI value ~S; expected one of ~S." value choices))
  value)

(defun %ui-default (kind property)
  (case property
    (:height (when (eq kind :progress) 4d0))
    (:grow (if (eq kind :spacer) 1d0 0d0))
    (:radius (if (eq kind :progress) 2d0 0d0))
    (:border 0d0)
    (:gap (if (eq kind :button) 4d0 0d0))
    (:padding '(0d0 0d0 0d0 0d0))
    (:align (if (member kind '(:row :button)) :center :start))
    (:justify :start)
    (:text "")
    (:font "sans")
    (:size (cond ((member kind '(:icon :circular-progress)) 16d0)))
    (:orientation :horizontal)
    (:thickness (if (eq kind :circular-progress) 2d0 1d0))
    (:color (case kind (:separator #x45475aff)
                  ((:progress :circular-progress) #x89b4faff)))
    (:track #x313244ff)
    (:value 0d0)))

(defun %ui-property (tree property)
  (getf tree property (%ui-default (getf tree :kind) property)))

(defun canonical-ui (tree)
  "Validate and copy a bounded UI tree. Omitted text styles remain inherited."
  (let ((count 0))
    (labels ((walk (node depth)
               (when (or (> (incf count) 512) (> depth 32))
                 (error "UI tree exceeds 512 nodes or depth 32."))
               (let* ((kind (progn (%ui-list node 64 "UI node") (getf node :kind)))
                      (common '(:kind :width :height :grow :background :border-color
                                :radius :border :key :on-click))
                      (extra
                        (case kind
                          ((:row :column :button) '(:children :gap :padding :align :justify))
                          (:stack '(:children))
                          (:text '(:text :size :line-height :color :font))
                          (:image '(:src))
                          (:icon '(:name :path :size :color))
                          ((:rect :spacer) nil)
                          (:separator '(:orientation :thickness :color))
                          (:progress '(:value :color :track))
                          (:circular-progress '(:size :thickness :value :color :track))
                          (otherwise (error "Unsupported UI kind ~S." kind))))
                      (result (list :kind kind)))
                 (%ui-properties node (append common extra))
                 (dolist (key (append (cdr common) extra))
                   (let* ((default (%ui-default kind key))
                          (value (getf node key default))
                          (normalized
                            (case key
                              ((:width :height :line-height) (%ui-length value t))
                              (:size (%ui-length value (eq kind :text)))
                              ((:grow :radius :border :gap :thickness) (%ui-length value))
                              ((:background :border-color :color) (%ui-color value t))
                              (:track (%ui-color value))
                              ((:key :on-click) (%ui-key value t))
                              (:padding (%ui-edges value))
                              ((:align :justify) (%ui-choice value '(:start :center :end)))
                              (:orientation (%ui-choice value '(:horizontal :vertical)))
                              (:text (%ui-string value 65536))
                              (:font (%ui-string value 128 nil))
                              (:src (%ui-string value 65536 nil))
                              (:name (%ui-string value 65536 nil))
                              (:path (if (null value) nil (%ui-string value 65536)))
                              (:value (max 0d0 (min 1d0 (%double-float value))))
                              (:children
                               (%ui-list value 512 "UI children")
                               (mapcar (lambda (child) (walk child (1+ depth))) value)))))
                     (unless (equal normalized default)
                       (setf result (nconc result (list key normalized))))))
                 result)))
      (walk tree 1))))

(defun ui (kind &rest properties)
  "Construct an immutable-by-ownership element declaration, never a native handle."
  (canonical-ui (cons :kind (cons kind properties))))

(defun canonical-shell-surface (arguments)
  (%ui-properties arguments '(:name :tree :width :height :anchors :margin :layer
                             :exclusive-zone :visible :output :background :color :font-size))
  (let ((anchors (getf arguments :anchors '(:top :left :right)))
        (visible (getf arguments :visible t)))
    (%ui-list anchors 4 "Shell anchors")
    (dolist (anchor anchors) (%ui-choice anchor '(:top :right :bottom :left)))
    (unless (= (length anchors) (length (remove-duplicates anchors)))
      (error "Duplicate shell anchor."))
    (unless (member visible '(t nil)) (error "Shell visibility must be T or NIL."))
    (list :name (%ui-key (getf arguments :name))
          :tree (canonical-ui (getf arguments :tree))
          :width (%ui-length (getf arguments :width 0))
          :height (%ui-length (getf arguments :height 0))
          :anchors (loop for edge in '(:top :right :bottom :left)
                         when (member edge anchors) collect edge)
          :margin (%ui-edges (getf arguments :margin 0) t)
          :layer (%ui-choice (getf arguments :layer :top) '(:background :bottom :top :overlay))
          :exclusive-zone (%ui-length (getf arguments :exclusive-zone 0) nil t)
          :visible visible
          :output (let ((output (getf arguments :output)))
                    (when output (%ui-string output 65536 nil)))
          :background (%ui-color (getf arguments :background #x1e1e2eff))
          :color (%ui-color (getf arguments :color #xcdd6f4ff))
          :font-size (%ui-length (getf arguments :font-size 13)))))

(defun shell-surface (name tree &rest options)
  "Own a retained shell surface and its click commands in this extension."
  (%effect :surface (canonical-shell-surface (list* :name name :tree tree options))))

(defun %ui-round (number)
  (if (minusp number) (- (floor (+ (- number) 0.5d0))) (floor (+ number 0.5d0))))

(defun %ui-rounded-rect (rect)
  (destructuring-bind (x y width height) rect
    (let ((left (%ui-round x)) (top (%ui-round y)))
      (list left top (max 0 (- (%ui-round (+ x width)) left))
            (max 0 (- (%ui-round (+ y height)) top))))))

(defun %ui-intersection (a b)
  (let ((x (max (first a) (first b))) (y (max (second a) (second b))))
    (list x y (max 0 (- (min (+ (first a) (third a)) (+ (first b) (third b))) x))
          (max 0 (- (min (+ (second a) (fourth a)) (+ (second b) (fourth b))) y)))))

(defun %ui-text-style (tree scale color size)
  (let ((logical-size (or (%ui-property tree :size) size)))
    (values (* logical-size scale)
            (coerce (ceiling (* (or (%ui-property tree :line-height)
                                    (* logical-size 1.3d0)) scale)) 'double-float)
            (or (%ui-property tree :color) color))))

(defun %ui-load-asset (asset-loader declaration tree)
  (unless (functionp asset-loader)
    (error "A visible UI asset requires an asset loader."))
  (multiple-value-bind (asset-id packed)
      (funcall asset-loader declaration tree)
    (unless (and (typep asset-id '(unsigned-byte 64)) (plusp asset-id))
      (error "UI asset loader returned an invalid asset identity: ~S." asset-id))
    (unless (typep packed '(unsigned-byte 64))
      (error "UI asset loader returned invalid packed dimensions: ~S." packed))
    (let ((asset-width (ldb (byte 32 32) packed))
          (asset-height (ldb (byte 32 0) packed)))
      (unless (and (/= packed #xffffffffffffffff)
                   (or (zerop packed) (and (plusp asset-width) (plusp asset-height))))
        (error "UI asset loader returned invalid packed dimensions: ~S." packed)))
    (values asset-id packed)))

(defun %ui-measure-tree (tree scale &optional (color #xffffffff) (size 14d0)
                                      asset-loader declaration)
  "Return a transient measured tree; native text measurement owns no surface."
  (let* ((kind (getf tree :kind))
         (children (mapcar (lambda (child)
                             (%ui-measure-tree child scale color size asset-loader declaration))
                           (getf tree :children)))
         (width 0d0) (height 0d0)
         (asset-id nil) (asset-available nil))
    (case kind
      ((:row :column :button)
       (let* ((horizontal (not (eq kind :column)))
              (padding (%ui-property tree :padding))
              (main (+ (* scale (%ui-property tree :gap) (max 0 (1- (length children))))
                       (loop for child in children sum (getf child (if horizontal :width :height)))))
              (cross (loop for child in children maximize (getf child (if horizontal :height :width)) into m
                           finally (return (or m 0d0)))))
         (setf width (+ (if horizontal main cross) (* scale (+ (second padding) (fourth padding))))
               height (+ (if horizontal cross main) (* scale (+ (first padding) (third padding)))))))
      (:stack
       (setf width (loop for child in children maximize (getf child :width) into m finally (return (or m 0d0)))
             height (loop for child in children maximize (getf child :height) into m finally (return (or m 0d0)))))
      (:text
       (multiple-value-bind (physical-size line-height rgba) (%ui-text-style tree scale color size)
         (declare (ignore rgba))
         (let ((packed (if (plusp physical-size)
                           (%ui-text-size (%ui-property tree :text) (%ui-property tree :font)
                                          physical-size (max 1d0 line-height))
                           (max 0 (ceiling line-height)))))
           (unless (and (typep packed '(unsigned-byte 64)) (/= packed #xffffffffffffffff))
             (error "Cannot measure UI text."))
           (setf width (coerce (ldb (byte 32 32) packed) 'double-float)
                 height (if (zerop line-height) 0d0
                            (coerce (ldb (byte 32 0) packed) 'double-float))))))
      (:separator
       (if (eq (%ui-property tree :orientation) :horizontal)
           (setf height (* scale (%ui-property tree :thickness)))
           (setf width (* scale (%ui-property tree :thickness)))))
      (:circular-progress
       (setf width (* scale (%ui-property tree :size)) height width))
      (:image
       (multiple-value-bind (id packed) (%ui-load-asset asset-loader declaration tree)
         (setf asset-id id
               asset-available (plusp packed)
               width (coerce (ldb (byte 32 32) packed) 'double-float)
               height (coerce (ldb (byte 32 0) packed) 'double-float))))
      (:icon
       (multiple-value-bind (id packed) (%ui-load-asset asset-loader declaration tree)
         (setf asset-id id
               asset-available (plusp packed)
               width (ceiling (* scale (%ui-property tree :size)))
               height width))))
    (when (%ui-property tree :width) (setf width (* scale (%ui-property tree :width))))
    (when (%ui-property tree :height) (setf height (* scale (%ui-property tree :height))))
    (let ((result (list :tree tree :width width :height height :children children)))
      (when (member kind '(:image :icon))
        (setf result (nconc result (list :asset-id asset-id :asset-available asset-available))))
      result)))

(defun %ui-asset-ids (measured)
  "Return measured asset IDs in generated-key/tree preorder, without duplicates."
  (let ((seen (make-hash-table :test #'eql)) (ids nil))
    (labels ((walk (node)
               (let ((id (getf node :asset-id)))
                 (when (and id (not (gethash id seen)))
                   (setf (gethash id seen) t)
                   (push id ids)))
               (dolist (child (getf node :children)) (walk child))))
      (walk measured))
    (nreverse ids)))

(defun %ui-draw-plan (measured width height scale background color size)
  (let ((draw nil) (hits nil) (serial 0) (indices (make-hash-table :test #'eq))
        (hit-keys (make-hash-table :test #'equal)))
    (labels ((index-tree (node)
               (setf (gethash node indices) (incf serial))
               (dolist (child (getf node :children)) (index-tree child)))
             (fill-rect (rect rgba radius stroke clip)
               (when (and rgba (plusp (logand rgba 255))
                          (plusp (third rect)) (plusp (fourth rect)))
                 (push (append (list :rect) rect (list rgba radius stroke (copy-list clip))) draw)))
             (place (node rect inherited-clip)
               (let* ((tree (getf node :tree)) (kind (getf tree :kind))
                      (box (%ui-rounded-rect rect))
                      (clip (%ui-intersection box inherited-clip))
                      (index (gethash node indices))
                      (radius (* scale (%ui-property tree :radius)))
                      (border (* scale (%ui-property tree :border))))
                 (when (and (plusp (third clip)) (plusp (fourth clip)))
                   (when (%ui-property tree :on-click)
                     (let ((key (if (%ui-property tree :key)
                                    (string-downcase (symbol-name (%ui-property tree :key)))
                                    (format nil "node-~D" index))))
                       (when (gethash key hit-keys)
                         (error "Duplicate shell click key ~S within one surface." key))
                       (setf (gethash key hit-keys) t)
                       (push (list :key key
                                   :command (string-downcase (symbol-name (%ui-property tree :on-click)))
                                   :x (first clip) :y (second clip) :width (third clip) :height (fourth clip)) hits)))
                   (fill-rect box (%ui-property tree :background) radius 0d0 clip)
                   (when (plusp border) (fill-rect box (%ui-property tree :border-color) radius border clip))
                   (case kind
                     ((:row :column :button)
                      (flex node rect clip (not (eq kind :column))))
                     (:stack (dolist (child (getf node :children)) (place child rect clip)))
                     (:text
                      (multiple-value-bind (physical-size line-height rgba) (%ui-text-style tree scale color size)
                        (when (and (plusp physical-size) (plusp line-height))
                          (push (list :text (first box) (second box) (copy-seq (%ui-property tree :text))
                                      (copy-seq (%ui-property tree :font)) physical-size line-height rgba (copy-list clip)) draw))))
                     (:image
                      (when (and (getf node :asset-available)
                                 (plusp (third box)) (plusp (fourth box)))
                        (push (list :asset (getf node :asset-id)
                                    (first box) (second box) (third box) (fourth box)
                                    nil 0 (copy-list clip)) draw)))
                     (:icon
                      (let ((px (min (third box) (fourth box))))
                        (when (plusp px)
                          (if (getf node :asset-available)
                              (let ((x (%ui-round (+ (first box) (/ (- (third box) px) 2d0))))
                                    (y (%ui-round (+ (second box) (/ (- (fourth box) px) 2d0)))))
                                (push (list :asset (getf node :asset-id) x y px px
                                            (not (null (%ui-property tree :color)))
                                            (or (%ui-property tree :color) 0) (copy-list clip)) draw))
                              (push (list :text (first box) (second box)
                                          (copy-seq (%ui-property tree :name)) "sans"
                                          (* 0.75d0 (fourth box))
                                          (coerce (fourth box) 'double-float)
                                          (or (%ui-property tree :color) #xffffffff)
                                          (copy-list clip)) draw)))))
                     (:separator (fill-rect box (%ui-property tree :color) 0d0 0d0 clip))
                     (:progress
                      (fill-rect box (%ui-property tree :track) radius 0d0 clip)
                      (fill-rect (list (first box) (second box)
                                       (%ui-round (* (third box) (%ui-property tree :value))) (fourth box))
                                 (%ui-property tree :color) radius 0d0 clip))
                     (:circular-progress
                      (let* ((thickness (* scale (%ui-property tree :thickness)))
                             (ring-radius (max 0d0 (/ (- (min (third box) (fourth box)) thickness) 2d0)))
                             (cx (+ (first box) (/ (third box) 2d0)))
                             (cy (+ (second box) (/ (fourth box) 2d0)))
                             (start (- (/ pi 2d0))))
                        (when (and (plusp thickness) (plusp ring-radius))
                          (push (list :arc cx cy ring-radius thickness start (+ start (* 2d0 pi))
                                      (%ui-property tree :track) (copy-list clip)) draw)
                          (when (plusp (%ui-property tree :value))
                            (push (list :arc cx cy ring-radius thickness start
                                        (+ start (* 2d0 pi (%ui-property tree :value)))
                                        (%ui-property tree :color) (copy-list clip)) draw)))))))))
             (flex (node rect clip horizontal)
               (let* ((tree (getf node :tree)) (children (getf node :children))
                      (padding (%ui-property tree :padding))
                      (x (+ (first rect) (* scale (fourth padding))))
                      (y (+ (second rect) (* scale (first padding))))
                      (w (max 0d0 (- (third rect) (* scale (+ (second padding) (fourth padding))))))
                      (h (max 0d0 (- (fourth rect) (* scale (+ (first padding) (third padding))))))
                      (inner-main (if horizontal w h)) (inner-cross (if horizontal h w))
                      (main-key (if horizontal :width :height)) (cross-key (if horizontal :height :width))
                      (gap (* scale (%ui-property tree :gap)))
                      (grow (loop for child in children sum (%ui-property (getf child :tree) :grow)))
                      (leftover (max 0d0 (- inner-main (* gap (max 0 (1- (length children))))
                                           (loop for child in children sum (getf child main-key)))))
                      (offset (if (plusp grow) 0d0
                                  (ecase (%ui-property tree :justify)
                                    (:start 0d0) (:center (/ leftover 2d0)) (:end leftover))))
                      (cursor (+ (if horizontal x y) offset))
                      (content-clip (%ui-intersection clip (%ui-rounded-rect (list x y w h)))))
                 (dolist (child children)
                   (let* ((main (+ (getf child main-key)
                                   (if (plusp grow) (* leftover (/ (%ui-property (getf child :tree) :grow) grow)) 0d0)))
                          (cross (if (eq (getf (getf child :tree) :kind) :separator)
                                     inner-cross (min inner-cross (getf child cross-key))))
                          (cross-position (+ (if horizontal y x)
                                             (ecase (%ui-property tree :align)
                                               (:start 0d0) (:center (/ (- inner-cross cross) 2d0))
                                               (:end (- inner-cross cross))))))
                     (place child (if horizontal (list cursor cross-position main cross)
                                     (list cross-position cursor cross main)) content-clip)
                     (incf cursor (+ main gap)))))))
      (index-tree measured)
      (fill-rect (list 0 0 width height) background 0d0 0d0 (list 0 0 width height))
      (place measured (list 0d0 0d0 (coerce width 'double-float) (coerce height 'double-float))
             (list 0 0 width height))
      (values (nreverse draw) (nreverse hits)))))

(defun %ui-reserve (area anchors amount)
  (let ((top (not (null (member :top anchors)))) (right (not (null (member :right anchors))))
        (bottom (not (null (member :bottom anchors)))) (left (not (null (member :left anchors)))))
    (cond ((and top (not bottom) (eq left right))
           (let ((delta (min amount (getf area :height))))
             (incf (getf area :y) delta) (decf (getf area :height) delta)))
          ((and bottom (not top) (eq left right))
           (decf (getf area :height) (min amount (getf area :height))))
          ((and left (not right) (eq top bottom))
           (let ((delta (min amount (getf area :width))))
             (incf (getf area :x) delta) (decf (getf area :width) delta)))
          ((and right (not left) (eq top bottom))
           (decf (getf area :width) (min amount (getf area :width)))))))

(defun resolve-shell-surfaces (declarations outputs workareas &optional asset-loader)
  "Return complete draw/hit plans and sequential reservations, without mutation."
  (%ui-list declarations 64 "Shell declarations")
  (%ui-list outputs 64 "Shell outputs")
  (let ((plans nil) (areas (copy-data workareas)) (seen nil) (pixels 0))
    (dolist (declaration declarations)
      (let* ((owner (%ui-string (getf declaration :owner) 65536 nil))
             (source-id (getf declaration :source-id))
             (name (%ui-key (getf declaration :name)))
             (identity (list owner name)))
        (unless (typep source-id '(unsigned-byte 64)) (error "Invalid shell source identity."))
        (when (member identity seen :test #'equal) (error "Duplicate owned shell surface ~S." name))
        (push identity seen)
        (when (getf declaration :visible)
          (dolist (output outputs)
            (when (or (null (getf declaration :output))
                      (equal (getf declaration :output) (getf output :name)))
              (let* ((scale (/ (%double-float (getf output :scale-120 120)) 120d0))
                     (anchors (getf declaration :anchors))
                     (margin (mapcar (lambda (n) (%ui-round (* n scale))) (getf declaration :margin)))
                     (ow (getf output :width)) (oh (getf output :height))
                     (measured (progn
                                 (unless (plusp scale) (error "Shell output scale must be positive."))
                                 (%ui-measure-tree (getf declaration :tree) scale
                                                   (getf declaration :color) (getf declaration :font-size)
                                                   asset-loader declaration)))
                     (width (max 1 (if (and (member :left anchors) (member :right anchors))
                                       (- ow (second margin) (fourth margin))
                                       (if (plusp (getf declaration :width))
                                           (%ui-round (* scale (getf declaration :width)))
                                           (ceiling (getf measured :width))))))
                     (height (max 1 (if (and (member :top anchors) (member :bottom anchors))
                                        (- oh (first margin) (third margin))
                                        (if (plusp (getf declaration :height))
                                            (%ui-round (* scale (getf declaration :height)))
                                            (ceiling (getf measured :height))))))
                     (x (+ (getf output :x)
                           (cond ((member :left anchors) (fourth margin))
                                 ((member :right anchors) (- ow width (second margin)))
                                 (t (truncate (- ow width) 2)))))
                     (y (+ (getf output :y)
                           (cond ((member :top anchors) (first margin))
                                 ((member :bottom anchors) (- oh height (third margin)))
                                 (t (truncate (- oh height) 2)))))
                     (area (find (getf output :name) areas :key (lambda (a) (getf a :name)) :test #'equal)))
                (unless (and (every (lambda (n) (typep n '(signed-byte 32))) (list x y width height))
                             (<= (* width height) (* 16 1024 1024)))
                  (error "Shell surface exceeds its physical canvas budget."))
                (incf pixels (* width height))
                (when (or (>= (length plans) 64) (> pixels (* 32 1024 1024)))
                  (error "Shell surface set exceeds its canvas budget."))
                (multiple-value-bind (draw hits)
                    (%ui-draw-plan measured width height scale (getf declaration :background)
                                   (getf declaration :color) (getf declaration :font-size))
                  (let ((plan (list :owner (copy-seq owner) :source-id source-id :name name
                                    :output (copy-seq (getf output :name)) :x x :y y
                                    :width width :height height :layer (getf declaration :layer))))
                    (let ((asset-ids (%ui-asset-ids measured)))
                      (when asset-ids
                        (setf plan (nconc plan (list :assets asset-ids)))))
                    (setf plan (nconc plan (list :draw draw :hits hits)))
                    (push plan plans)))
                (when (and area (plusp (getf declaration :exclusive-zone)))
                  (%ui-reserve area anchors (%ui-round (* scale (getf declaration :exclusive-zone)))))))))))
    (values (nreverse plans) areas)))
